package server

import (
	"crypto/rand"
	"encoding/json"
    "errors"
    "fmt"
    "net/http"
    "os"
    "path/filepath"
    "strings"
    "sync"
    "time"
)

type Config struct { Address, ClientKey, ServerID, ContainerName, ContainerID, PreviewOrigin, WorkspaceRoot, ExecutionMode, ModelCommand, TestCommand, StatePath string; PreviewPorts []int; CommandTimeout int }
type Task struct { ID string `json:"id"`; Title string `json:"title"`; AppName string `json:"appName"`; Prompt string `json:"prompt"`; Repository string `json:"repository"`; OwnedPaths []string `json:"ownedPaths"`; Status string `json:"status"`; CreatedAt string `json:"createdAt"`; Report string `json:"report"`; PreviewURL string `json:"previewUrl,omitempty"`; ChangedFiles []string `json:"changedFiles,omitempty"`; TestOutput string `json:"testOutput,omitempty"`; Diff string `json:"diff,omitempty"` }
type Artifact struct { ID string `json:"id"`; Name string `json:"name"`; Kind string `json:"kind"`; Status string `json:"status"` }
type Skill struct { ID string `json:"id"`; Name string `json:"name"`; Enabled bool `json:"enabled"` }
type Store struct { sync.RWMutex; tasks map[string]Task; artifacts map[string]Artifact; skills map[string]Skill; nextPreview int; config Config }
type App struct { store *Store; config Config }

func ConfigFromEnvironment() Config { return Config{Address: env("CXFORGE_ADDRESS", ":6400"), ClientKey: env("CXFORGE_ZUNO_CLIENT_KEY", "local-zuno-to-cxforge-client-key-32chars"), ServerID: env("CXFORGE_SERVER_ID", "00000000-0000-4000-8000-000000000001"), ContainerName: env("CXFORGE_CONTAINER_NAME", "cxforge"), ContainerID: env("HOSTNAME", "local"), PreviewOrigin: env("CXFORGE_PREVIEW_ORIGIN", "http://127.0.0.1"), PreviewPorts: []int{7300, 7301, 7302, 7303}, WorkspaceRoot: env("CXFORGE_WORKSPACE_ROOT", "/workspace"), ExecutionMode: env("CXFORGE_EXECUTION_MODE", "blocked"), ModelCommand: os.Getenv("CXFORGE_MODEL_COMMAND"), TestCommand: os.Getenv("CXFORGE_TEST_COMMAND"), StatePath: env("CXFORGE_STATE_PATH", "/workspace/.cxforge-state.json"), CommandTimeout: 300} }

func New(config Config) *App { store := &Store{tasks: map[string]Task{}, artifacts: map[string]Artifact{}, skills: map[string]Skill{}, config: config}; for _, skill := range []Skill{{"repo.read", "Read repository", true}, {"code.edit", "Edit owned files", true}, {"code.test", "Run tests", true}, {"preview.web", "Start preview", true}} { store.skills[skill.ID] = skill }; return &App{store: store, config: config} }

func (app *App) Handler() http.Handler { mux := http.NewServeMux(); mux.HandleFunc("GET /", app.welcome); mux.HandleFunc("GET /api/v1/cxforge/health", app.health); mux.HandleFunc("GET /api/v1/cxforge/runner/health", app.runnerHealth); mux.HandleFunc("GET /api/v1/cxforge/control/overview", app.auth(app.overview)); mux.HandleFunc("GET /api/v1/cxforge/control/skills", app.auth(app.skills)); mux.HandleFunc("PUT /api/v1/cxforge/control/skills", app.auth(app.updateSkills)); mux.HandleFunc("POST /api/v1/cxforge/control/tasks", app.auth(app.createTask)); mux.HandleFunc("POST /api/v1/cxforge/control/tasks/", app.auth(app.taskAction)); return logging(mux) }
func (app *App) welcome(w http.ResponseWriter, _ *http.Request) { w.Header().Set("Content-Type", "text/html; charset=utf-8"); _, _ = w.Write([]byte("<!doctype html><meta name=viewport content='width=device-width'><title>CXForge</title><style>body{font:16px system-ui;background:#101412;color:#edf5ef;display:grid;place-items:center;height:100vh}main{max-width:520px;padding:42px;border:1px solid #334439;border-radius:18px}strong{color:#70d493}</style><main><h1>CXForge</h1><p><strong>Worker server ready.</strong></p><p>Connect Zuno to submit isolated coding tasks.</p></main>")) }
func (app *App) health(w http.ResponseWriter, _ *http.Request) { jsonResponse(w, http.StatusOK, map[string]any{"status": "ok", "providers": []string{"cxforge.worker"}}) }
func (app *App) runnerHealth(w http.ResponseWriter, _ *http.Request) { jsonResponse(w, http.StatusOK, map[string]string{"status": "ready"}) }
func (app *App) overview(w http.ResponseWriter, _ *http.Request) { app.store.RLock(); defer app.store.RUnlock(); tasks := make([]Task, 0, len(app.store.tasks)); for _, task := range app.store.tasks { tasks = append(tasks, task) }; artifacts := make([]Artifact, 0, len(app.store.artifacts)); for _, item := range app.store.artifacts { artifacts = append(artifacts, item) }; skills := make([]Skill, 0, len(app.store.skills)); for _, item := range app.store.skills { skills = append(skills, item) }; jsonResponse(w, http.StatusOK, map[string]any{"agents": []map[string]any{{"id": "agent-" + app.config.ServerID[:8], "name": "CXForge worker", "status": "ready", "capabilities": []string{"workspace", "runner", "preview"}}}, "artifacts": artifacts, "components": []string{"api", "runner", "workspace", "model", "tests", "preview"}, "containerId": app.config.ContainerID, "containerName": app.config.ContainerName, "mode": "local-edge", "previewPorts": app.config.PreviewPorts, "runnerUrl": "http://127.0.0.1:6402", "serverId": app.config.ServerID, "skills": skills, "tasks": tasks}) }
func (app *App) skills(w http.ResponseWriter, _ *http.Request) { app.store.RLock(); defer app.store.RUnlock(); items := make([]Skill, 0, len(app.store.skills)); for _, item := range app.store.skills { items = append(items, item) }; jsonResponse(w, http.StatusOK, items) }
func (app *App) updateSkills(w http.ResponseWriter, r *http.Request) { var input struct { Skills []struct { ID string `json:"id"`; Enabled bool `json:"enabled"` } `json:"skills"` }; if err := decode(r, &input); err != nil { jsonError(w, 400, err); return }; app.store.Lock(); defer app.store.Unlock(); for _, update := range input.Skills { item, ok := app.store.skills[update.ID]; if ok { item.Enabled = update.Enabled; app.store.skills[update.ID] = item } }; skills := make([]Skill, 0, len(app.store.skills)); for _, item := range app.store.skills { skills = append(skills, item) }; jsonResponse(w, 200, skills) }
func (app *App) createTask(w http.ResponseWriter, r *http.Request) { var task Task; if err := decode(r, &task); err != nil || strings.TrimSpace(task.Title) == "" || strings.TrimSpace(task.Prompt) == "" || strings.TrimSpace(task.Repository) == "" || len(task.OwnedPaths) == 0 { jsonError(w, 400, errors.New("title, prompt, repository, and ownedPaths are required")); return }; task.ID = newID(); task.Status = "draft"; task.CreatedAt = time.Now().UTC().Format(time.RFC3339); task.Report = "Task contract created and waiting for worker execution."; app.store.Lock(); app.store.tasks[task.ID] = task; app.store.Unlock(); jsonResponse(w, 201, task) }
func (app *App) taskAction(w http.ResponseWriter, r *http.Request) { id, action, ok := parseTaskAction(r.URL.Path); if !ok { jsonError(w, 404, errors.New("unknown task action")); return }; switch action { case "queue": app.queueTask(w, id); case "approve": app.reviewTask(w, id, "approved", "Review approved in Zuno. Ready for the next governed merge step."); case "reject": app.reviewTask(w, id, "rejected", "Review rejected in Zuno. Worker output needs revision before merge."); default: jsonError(w, 404, errors.New("unknown task action")) } }
func (app *App) queueTask(w http.ResponseWriter, id string) { app.store.Lock(); task, ok := app.store.tasks[id]; if !ok || task.Status != "draft" { app.store.Unlock(); jsonError(w, 409, errors.New("only a draft task can enter the worker queue")); return }; port := app.config.PreviewPorts[app.store.nextPreview%len(app.config.PreviewPorts)]; app.store.nextPreview++; task.Status, task.PreviewURL, task.Report = "queued", fmt.Sprintf("%s:%d/preview/%s", app.config.PreviewOrigin, port, id), "Accepted by CXForge. Workspace preparation is queued."; app.store.tasks[id] = task; app.store.artifacts[id+":workspace"] = Artifact{id+":workspace", "Workspace "+id[:8], "workspace", "pending"}; app.store.Unlock(); go app.execute(task); jsonResponse(w, 200, task) }
func (app *App) reviewTask(w http.ResponseWriter, id, status, report string) { app.store.Lock(); defer app.store.Unlock(); task, ok := app.store.tasks[id]; if !ok { jsonError(w, 404, errors.New("task not found")); return }; if task.Status != "review" { jsonError(w, 409, errors.New("only a task in review can be approved or rejected")); return }; task.Status, task.Report = status, report; app.store.tasks[id] = task; jsonResponse(w, 200, task) }
func (app *App) execute(task Task) { app.store.Lock(); task.Status, task.Report = "running", "Preparing isolated workspace."; app.store.tasks[task.ID] = task; app.store.Unlock(); repository := filepath.Join(app.config.WorkspaceRoot, task.ID, filepath.Clean(task.Repository)); if !within(app.config.WorkspaceRoot, repository) { app.finish(task, "blocked", "Repository is outside the workspace root."); return }; if err := os.MkdirAll(repository, 0o755); err != nil { app.finish(task, "blocked", "Could not prepare workspace: "+err.Error()); return }; if app.config.ExecutionMode != "demo" { app.finish(task, "blocked", "No model executor is configured. Set CXFORGE_EXECUTION_MODE=demo for local smoke tests, then add a model adapter before production."); return }; target := filepath.Join(repository, filepath.Clean(task.OwnedPaths[0])); if !within(repository, target) { app.finish(task, "blocked", "Owned path escapes repository."); return }; err := os.MkdirAll(filepath.Dir(target), 0o755); if err == nil { err = os.WriteFile(target, []byte("CXForge demo edit\n"), 0o644) }; if err != nil { app.finish(task, "blocked", "Demo edit failed: "+err.Error()); return }; app.finish(task, "review", "Demo execution completed. One owned file was edited; connect a model adapter for real coding.") }
func (app *App) finish(task Task, status, report string) { app.store.Lock(); defer app.store.Unlock(); task.Status, task.Report = status, report; app.store.tasks[task.ID] = task; artifact := app.store.artifacts[task.ID+":workspace"]; artifact.Status = "ready"; app.store.artifacts[task.ID+":workspace"] = artifact }
func (app *App) auth(next http.HandlerFunc) http.HandlerFunc { return func(w http.ResponseWriter, r *http.Request) { if r.Header.Get("X-CXForge-Client-Key") != app.config.ClientKey { jsonError(w, 401, errors.New("authentication required")); return }; next(w, r) } }
func decode(r *http.Request, target any) error { defer r.Body.Close(); return json.NewDecoder(http.MaxBytesReader(nil, r.Body, 1<<20)).Decode(target) }
func jsonResponse(w http.ResponseWriter, status int, value any) { w.Header().Set("Content-Type", "application/json"); w.WriteHeader(status); _ = json.NewEncoder(w).Encode(value) }
func jsonError(w http.ResponseWriter, status int, err error) { jsonResponse(w, status, map[string]string{"error": err.Error()}) }
func logging(next http.Handler) http.Handler { return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) { start := time.Now(); next.ServeHTTP(w, r); fmt.Printf("%s %s %s\n", r.Method, r.URL.Path, time.Since(start)) }) }
func env(key, fallback string) string { if value := os.Getenv(key); value != "" { return value }; return fallback }
func newID() string { bytes := make([]byte, 16); if _, err := rand.Read(bytes); err != nil { return fmt.Sprintf("00000000-0000-4000-8000-%012d", time.Now().UnixNano()%1_000_000_000_000) }; bytes[6] = (bytes[6] & 0x0f) | 0x40; bytes[8] = (bytes[8] & 0x3f) | 0x80; return fmt.Sprintf("%08x-%04x-%04x-%04x-%012x", bytes[0:4], bytes[4:6], bytes[6:8], bytes[8:10], bytes[10:16]) }
func within(root, candidate string) bool { relative, err := filepath.Rel(filepath.Clean(root), filepath.Clean(candidate)); return err == nil && relative != ".." && !strings.HasPrefix(relative, ".."+string(filepath.Separator)) }
func parseTaskAction(path string) (string, string, bool) { parts := strings.Split(strings.TrimPrefix(path, "/api/v1/cxforge/control/tasks/"), "/"); if len(parts) != 2 || parts[0] == "" || parts[1] == "" { return "", "", false }; return parts[0], parts[1], true }
