export const projectsModuleManifest = {
  capabilities: [
    'project-switcher',
    'project-context',
    'empty-project-onboarding',
    'project-properties',
    'project-identity-settings',
    'repository-browser',
    'project-rename',
    'project-archive',
    'repository-binding',
  ],
  dependencies: {
    'zetro.developer-tools.web': '^1.0.0',
    'zetro.git-delivery.web': '^0.1.0',
    'zetro.projects.api': '^0.5.0',
    'zetro.desk.web': '^0.8.0',
  },
  id: 'zetro.projects.web',
  lifecycle: {
    activate: 'Load projects and mount the project switcher.',
    deactivate: 'Unmount project controls and discard transient selection.',
    install: 'No browser business data is created.',
    uninstall: 'No API project records are removed.',
    upgrade: 'Add isolated Git delivery settings to the project properties layer.',
  },
  publicContracts: ['ProjectProvider', 'ProjectSwitcher', 'useProjects'],
  scope: 'zetro-web',
  version: '0.5.0',
} as const
