export const agentChatModuleManifest = {
  capabilities: [
    'agent-chat',
    'conversation-history',
    'conversation-archive',
    'safe-markdown-history',
    'message-actions',
    'connected-folder',
    'active-turn-stop',
    'send-response-to-task',
    'multimodal-prompt',
    'centralized-workflow-default',
    'codex-model-selector',
    'drag-drop-attachments',
    'clipboard-attachments',
    'long-paste-attachment',
  ],
  dependencies: {
    'zetro.chat.api': '^0.16.2',
    'zetro.desk.web': '^0.8.0',
    'zetro.projects.web': '^0.5.0',
    'zetro.project-tasks.web': '^0.4.2',
    'zetro.settings.web': '^0.6.0',
  },
  id: 'zetro.agent-chat.web',
  lifecycle: {
    activate: 'Mount agent chat inside the Zetro Desk surfaces.',
    deactivate: 'Unmount agent chat and stop active browser voice input.',
    install: 'No browser business data is created.',
    uninstall: 'No API conversation history is removed.',
    upgrade: 'Version 0.12.1 accepts bounded command failure details in responses and history.',
  },
  publicContracts: ['AgentChatProvider', 'AgentChatHistory', 'AgentChatWorkspace'],
  scope: 'zetro-web',
  version: '0.13.5',
} as const
