export const agentChatModuleManifest = {
  capabilities: [
    'agent-chat',
    'conversation-history',
    'conversation-archive',
    'safe-markdown-history',
    'message-actions',
    'connected-folder',
    'active-turn-stop',
    'send-response-to-task',
    'multimodal-prompt',
    'centralized-workflow-default',
  ],
  dependencies: {
    'zetro.chat.api': '^0.11.0',
    'zetro.desk.web': '^0.7.0',
    'zetro.projects.web': '^0.5.0',
    'zetro.project-tasks.web': '^0.4.1',
    'zetro.settings.web': '^0.3.0',
  },
  id: 'zetro.agent-chat.web',
  lifecycle: {
    activate: 'Mount agent chat inside the Zetro Desk surfaces.',
    deactivate: 'Unmount agent chat and stop active browser voice input.',
    install: 'No browser business data is created.',
    uninstall: 'No API conversation history is removed.',
    upgrade: 'Version 0.10.0 renders assistant Markdown as safe semantic HTML.',
  },
  publicContracts: ['AgentChatProvider', 'AgentChatHistory', 'AgentChatWorkspace'],
  scope: 'zetro-web',
  version: '0.10.1',
} as const
