export const developerToolsModuleManifest = {
  capabilities: [
    'floating-git-monitor',
    'branch-compare',
    'branch-create',
    'commit',
    'push',
    'revert-commit',
    'external-editor',
    'file-browser',
    'terminal-launch',
    'global-settings',
    'project-settings',
    'repository-workspace',
    'file-and-hunk-staging',
    'side-by-side-diff',
    'history-and-blame',
    'conflict-resolution',
    'repository-task-runner',
    'branch-and-stash-management',
    'pull-request-create',
  ],
  dependencies: { 'zetro.developer-tools.api': '^1.0.0' },
  id: 'zetro.developer-tools.web',
  lifecycle: {
    activate: 'Monitor the selected repository while Zetro is visible.',
    deactivate: 'Stop polling and unmount developer tool controls.',
    install: 'Load API-owned global and project settings.',
    uninstall: 'Leave repositories and settings unchanged.',
    upgrade: 'Version 1.0.0 adds the complete repository review and recovery workspace.',
  },
  publicContracts: [
    'DeveloperToolsProvider',
    'DeveloperToolsPanel',
    'GlobalDeveloperToolSettings',
    'ProjectDeveloperToolSettings',
    'useDeveloperTools',
  ],
  scope: 'zetro-web',
  version: '1.0.0',
} as const
