import { ArrowLeftIcon } from "lucide-react";
import { Seo } from "./seo";

type LegalPage = "privacy" | "terms" | "cookies";
const content: Record<LegalPage, { title: string; intro: string; sections: { heading: string; body: string }[] }> = {
  privacy: { title: "Privacy policy", intro: "A plain-language overview of how the Sites public portal handles information.", sections: [{ heading: "What we collect", body: "The public pages do not require an account. If analytics consent is granted, anonymous page usage data may be sent to Google Analytics to help improve the experience." }, { heading: "How we use information", body: "We use information to keep the portal reliable, understand page usefulness, and respond to messages sent through a future contact workflow. We do not sell personal information." }, { heading: "Your choices", body: "You can decline analytics when the consent notice appears. You can also clear the Sites analytics consent entry in your browser at any time." }] },
  terms: { title: "Terms of use", intro: "The basic terms for using the Sites public client portal.", sections: [{ heading: "Use of the portal", body: "You may browse and use these public pages for lawful purposes. Do not attempt to disrupt the service, probe protected endpoints, or use content in a way that misrepresents its source." }, { heading: "Content", body: "Client names, descriptions, marks, and portfolio content are presented for their respective client spaces. Content may change as the CMS develops." }, { heading: "Availability", body: "The portal is provided as an evolving service. We may update, pause, or remove pages while maintaining reasonable care for published content." }] },
  cookies: { title: "Cookie notice", intro: "How this portal uses browser storage and optional analytics.", sections: [{ heading: "Essential browser storage", body: "The portal stores an analytics preference in local storage so it can remember whether you accepted or declined optional analytics." }, { heading: "Optional analytics", body: "Google Analytics is not loaded unless you explicitly allow it. When enabled, the integration requests anonymized IP handling." }, { heading: "Managing preferences", body: "Clear your browser's local storage for this site to show the consent choice again, then select a different preference." }] },
};

export function LegalPage({ kind }: { kind: LegalPage }) {
  const page = content[kind];
  return <><Seo title={`${page.title} | Sites`} description={page.intro} /><main className="mx-auto max-w-3xl px-6 pb-24 pt-12 lg:px-10"><a className="inline-flex items-center gap-2 text-sm text-slate-500 hover:text-white" href="/clients"><ArrowLeftIcon className="size-4" /> Back to client portal</a><p className="mt-16 text-sm uppercase tracking-[0.24em] text-cyan-300">Sites / legal</p><h1 className="mt-4 text-5xl font-semibold tracking-[-0.05em] text-white">{page.title}</h1><p className="mt-6 text-lg leading-8 text-slate-400">{page.intro}</p><div className="mt-16 space-y-10">{page.sections.map((section) => <section key={section.heading} className="border-t border-white/10 pt-6"><h2 className="text-xl font-semibold text-white">{section.heading}</h2><p className="mt-3 leading-8 text-slate-400">{section.body}</p></section>)}</div><p className="mt-16 text-sm text-slate-500">Last updated: September 24, 2026</p></main></>;
}
