import type { InterfaceTopologySection } from '@codexsun/ui/features/interface-topology'

export const zetroTopologySections: readonly InterfaceTopologySection[] = [
  {
    id: '11',
    technicalName: 'zetro.chat.workspace',
    name: 'Chat workspace',
    scope: 'Zetro',
    description: 'Hosts conversation history, message stream, and composer.',
  },
  {
    id: '11.1',
    technicalName: 'zetro.history.drawer',
    name: 'Conversation history',
    scope: 'Chat workspace',
    description: 'Lists pinned and recent conversations.',
  },
  {
    id: '11.1.1',
    technicalName: 'zetro.history.railToggle',
    name: 'History rail toggle',
    scope: 'Conversation history',
    description: 'Collapses or expands the conversation rail.',
  },
  {
    id: '11.1.2',
    technicalName: 'zetro.history.conversationList',
    name: 'Conversation list',
    scope: 'Conversation history',
    description: 'Shows saved conversations and their actions.',
  },
  {
    id: '11.1.3',
    technicalName: 'zetro.history.newChat',
    name: 'History new chat',
    scope: 'Conversation history',
    description: 'Starts a new conversation.',
  },
  {
    id: '11.2',
    technicalName: 'zetro.conversation.stage',
    name: 'Conversation stage',
    scope: 'Chat workspace',
    description: 'Shows the empty prompt banner or active messages.',
  },
  {
    id: '11.2.1',
    technicalName: 'zetro.conversation.starterBanner',
    name: 'Starter banner',
    scope: 'Conversation stage',
    description: 'Introduces Zetro and suggests workflow-specific prompts.',
  },
  {
    id: '11.2.2',
    technicalName: 'zetro.conversation.messageList',
    name: 'Message list',
    scope: 'Conversation stage',
    description: 'Shows user and assistant messages and execution records.',
  },
  {
    id: '11.3',
    technicalName: 'zetro.composer.container',
    name: 'Message composer',
    scope: 'Chat workspace',
    description: 'Collects workflow, prompt, attachments, voice, and send actions.',
  },
  {
    id: '11.3.1',
    technicalName: 'zetro.composer.workflowSelector',
    name: 'Workflow selector',
    scope: 'Message composer',
    description: 'Selects Deliver, Develop, Document, Review, or Test.',
  },
  {
    id: '11.3.2',
    technicalName: 'zetro.composer.promptInput',
    name: 'Prompt input',
    scope: 'Message composer',
    description: 'Collects the message sent to Zetro.',
  },
  {
    id: '11.3.3',
    technicalName: 'zetro.composer.attachmentButton',
    name: 'Attachment button',
    scope: 'Message composer',
    description: 'Adds images, audio, or files.',
  },
  {
    id: '11.3.4',
    technicalName: 'zetro.composer.voiceButton',
    name: 'Voice input button',
    scope: 'Message composer',
    description: 'Starts or stops speech input.',
  },
  {
    id: '11.3.5',
    technicalName: 'zetro.composer.sendButton',
    name: 'Send message button',
    scope: 'Message composer',
    description: 'Sends the current message and attachments.',
  },
  {
    id: '12',
    technicalName: 'zetro.tasks.workspace',
    name: 'Task workspace',
    scope: 'Zetro',
    description: 'Shows execution tasks beside the conversation.',
  },
  {
    id: '12.1',
    technicalName: 'zetro.tasks.summaryBanner',
    name: 'Task summary banner',
    scope: 'Task workspace',
    description: 'Shows the task title and open count.',
  },
  {
    id: '12.2',
    technicalName: 'zetro.tasks.createControl',
    name: 'Task create control',
    scope: 'Task workspace',
    description: 'Opens or submits the task form.',
  },
  {
    id: '12.3',
    technicalName: 'zetro.tasks.taskList',
    name: 'Task list',
    scope: 'Task workspace',
    description: 'Shows task status, title, and priority.',
  },
  {
    id: '13',
    technicalName: 'zetro.settings.workspace',
    name: 'Connection settings',
    scope: 'Zetro',
    description: 'Manages the local Codex account connection.',
  },
  {
    id: '13.1',
    technicalName: 'zetro.settings.summaryBanner',
    name: 'Settings summary banner',
    scope: 'Connection settings',
    description: 'Introduces the Codex connection and refresh action.',
  },
  {
    id: '13.1.1',
    technicalName: 'zetro.settings.refreshButton',
    name: 'Refresh connection',
    scope: 'Settings summary banner',
    description: 'Refreshes local Codex connection status.',
  },
  {
    id: '13.2',
    technicalName: 'zetro.settings.accountCard',
    name: 'Account status card',
    scope: 'Connection settings',
    description: 'Shows current connection state and disconnect controls.',
  },
  {
    id: '13.3',
    technicalName: 'zetro.settings.deviceFlow',
    name: 'Device connection flow',
    scope: 'Connection settings',
    description: 'Generates and activates a device sign-in code.',
  },
  {
    id: '13.3.1',
    technicalName: 'zetro.settings.generateCode',
    name: 'Generate device code',
    scope: 'Device connection flow',
    description: 'Starts a new device authorization flow.',
  },
  {
    id: '13.3.2',
    technicalName: 'zetro.settings.browserLink',
    name: 'Open sign-in page',
    scope: 'Device connection flow',
    description: 'Opens the secure Codex sign-in page.',
  },
  {
    id: '13.3.3',
    technicalName: 'zetro.settings.copyCode',
    name: 'Copy device code',
    scope: 'Device connection flow',
    description: 'Copies the device authorization code.',
  },
  {
    id: '13.3.4',
    technicalName: 'zetro.settings.activationForm',
    name: 'Activation form',
    scope: 'Device connection flow',
    description: 'Updates authorization after browser approval.',
  },
  {
    id: '13.4',
    technicalName: 'zetro.settings.privacyBanner',
    name: 'Credential privacy banner',
    scope: 'Connection settings',
    description: 'Explains local credential storage boundaries.',
  },
  {
    id: '14',
    technicalName: 'zetro.customization.panel',
    name: 'Customization panel',
    scope: 'Zetro',
    description: 'Controls spacing, accent, task rail, and spoken replies.',
  },
]
