export const chatModuleManifest = {
  capabilities: [
    'conversation-history',
    'conversation-pin',
    'conversation-rename',
    'multimodal-composer',
    'speech-input',
    'speech-output',
    'isolated-task-summary',
    'coding-tool-activity',
    'task-workflow-selector',
    'delivery-pipeline-guide',
    'delivery-progress-record',
  ],
  dependencies: { 'zetro.chat.api': '^0.5.0' },
  id: 'zetro.chat.web',
  lifecycle: {
    activate: 'Mount the Zetro conversation workspace.',
    deactivate: 'Stop active browser speech and unmount the workspace.',
    install: 'No persistent business data is created.',
    uninstall: 'No business data is removed.',
    upgrade: 'Version 0.5.0 displays persisted delivery progress and evidence.',
  },
  publicContracts: ['ChatWorkspace', 'DeliveryPipeline', 'HistoryDrawer', 'WorkflowSelector'],
  scope: 'zetro-web',
  version: '0.5.0',
} as const
