export const commonModuleTableNames = {
  countries: "common_countries",
  states: "common_states",
  districts: "common_districts",
  cities: "common_cities",
  pincodes: "common_pincodes",
  contactGroups: "common_contact_groups",
  contactTypes: "common_contact_types",
  productGroups: "common_product_groups",
  productCategories: "common_product_categories",
  productTypes: "common_product_types",
  units: "common_units",
  hsnCodes: "common_hsn_codes",
  taxes: "common_taxes",
  brands: "common_brands",
  colours: "common_colours",
  sizes: "common_sizes",
  currencies: "common_currencies",
  orderTypes: "common_order_types",
  styles: "common_styles",
  transports: "common_transports",
  warehouses: "common_warehouses",
  destinations: "common_destinations",
  paymentTerms: "common_payment_terms",
  storefrontTemplates: "common_storefront_templates",
  sliderThemes: "common_slider_themes",
} as const

export const coreTableNames = {
  bootstrapSnapshots: "core_bootstrap_snapshots",
  companies: "core_companies",
  contacts: "core_contacts",
  commonModuleMetadata: "core_common_module_metadata",
  commonModuleItems: "core_common_module_items",
  ...commonModuleTableNames,
  authUsers: "auth_users",
  authPermissions: "auth_permissions",
  authRoles: "auth_roles",
  authUserRoles: "auth_user_roles",
  authRolePermissions: "auth_role_permissions",
  authSessions: "auth_sessions",
  authContactVerifications: "auth_contact_verifications",
  mailboxTemplates: "mailbox_templates",
  mailboxMessages: "mailbox_messages",
  mailboxMessageRecipients: "mailbox_message_recipients",
} as const
