export const coreTableNames = {
  bootstrapSnapshots: "core_bootstrap_snapshots",
  companies: "core_companies",
  contacts: "core_contacts",
  commonModuleMetadata: "core_common_module_metadata",
  commonModuleItems: "core_common_module_items",
  authUsers: "auth_users",
  authPermissions: "auth_permissions",
  authRoles: "auth_roles",
  authUserRoles: "auth_user_roles",
  authRolePermissions: "auth_role_permissions",
  authSessions: "auth_sessions",
  authContactVerifications: "auth_contact_verifications",
  mailboxTemplates: "mailbox_templates",
  mailboxMessages: "mailbox_messages",
  mailboxMessageRecipients: "mailbox_message_recipients",
} as const
