// Generated by @codexsun/app-cli. Do not edit manually.

export type MdiCatalogApplication = {
  icon: string;
  id: string;
  label: string;
  localUrlKey: string;
  path: string;
};

export const mdiCatalogApplications: readonly MdiCatalogApplication[] = [
  {
    "icon": "docs",
    "id": "docs",
    "label": "Docs",
    "localUrlKey": "VITE_DOCS_WEB_URL",
    "path": "/"
  },
  {
    "icon": "platform",
    "id": "platform",
    "label": "Platform",
    "localUrlKey": "VITE_PLATFORM_WEB_URL",
    "path": "/system"
  },
  {
    "icon": "application",
    "id": "qcafe",
    "label": "Q Cafe",
    "localUrlKey": "VITE_QCAFE_WEB_URL",
    "path": "/"
  },
  {
    "icon": "uiux",
    "id": "uiux",
    "label": "UIUX",
    "localUrlKey": "VITE_UIUX_WEB_URL",
    "path": "/"
  },
  {
    "icon": "zetro",
    "id": "zetro",
    "label": "Zetro",
    "localUrlKey": "VITE_ZETRO_WEB_URL",
    "path": "/zetro"
  }
] as const;
