import { randomUUID } from "node:crypto";
import { createLifecycleChecksum, MigrationRunner, type KyselyDataProvider } from "@codexsun/platform-core";
import type { Generated, Kysely, Selectable, Transaction } from "kysely";
import type { ApplicationSource, DeploymentOperation, DeploymentProviderKind, DeploymentRecord, DeploymentTarget, EnvironmentVariable, ProviderSummary } from "./provider.js";

export type DeploymentDatabase = {
  orship_deployment_providers: { id: string; name: string; kind: string; base_url: string; access_token_reference: string; status: string; created_at: string; updated_at: string };
  orship_deployment_targets: { id: string; provider_id: string; name: string; provider_target_id: string; address: string; production: number; status: string; created_at: string; updated_at: string };
  orship_deployment_applications: { id: string; target_id: string; name: string; source_type: string; source_json: string; provider_application_id: string; status: string; created_at: string; updated_at: string };
  orship_application_environments: { id: string; application_id: string; name: string; variables_json: string; created_at: string; updated_at: string };
  orship_deployments: { id: string; application_id: string; target_id: string; operation: string; status: string; provider_deployment_id: string | null; rollback_of: string | null; actor_id: string; correlation_id: string; message: string | null; created_at: string; updated_at: string };
  orship_deployment_events: { id: Generated<number>; deployment_id: string; event_type: string; message: string; outcome: string; actor_id: string; correlation_id: string; occurred_at: string };
  orship_deployment_logs: { id: Generated<number>; deployment_id: string; provider_log_reference: string | null; line_count: number; last_seen_at: string; };
  orship_rollback_references: { id: string; deployment_id: string; source_deployment_id: string; provider_rollback_id: string; created_at: string };
  orship_health_results: { id: Generated<number>; target_id: string; application_id: string | null; status: string; summary: string; checked_at: string; correlation_id: string };
  orship_deployment_audit_events: { id: string; actor_id: string; target_id: string | null; application_id: string | null; operation: string; result: string; correlation_id: string; occurred_at: string };
};

type Database = Kysely<DeploymentDatabase>;
type MigrationDatabase = Database | Transaction<DeploymentDatabase>;
type ProviderRow = Selectable<DeploymentDatabase["orship_deployment_providers"]>;
type TargetRow = Selectable<DeploymentDatabase["orship_deployment_targets"]>;
type ApplicationRow = Selectable<DeploymentDatabase["orship_deployment_applications"]>;
type DeploymentRow = Selectable<DeploymentDatabase["orship_deployments"]>;
export type DeploymentApplicationRow = ApplicationRow;

const migration = {
  id: "orship.deployments.001",
  owner: "orship.deployments",
  description: "deployment providers, targets, applications, deployments, events, logs, health, and audit state",
  checksum: createLifecycleChecksum("deployment providers, targets, applications, deployments, events, logs, health, and audit state"),
  async apply(database: MigrationDatabase): Promise<void> {
    await database.schema.createTable("orship_deployment_providers").ifNotExists().addColumn("id", "varchar(36)", (c) => c.primaryKey()).addColumn("name", "varchar(160)", (c) => c.notNull()).addColumn("kind", "varchar(32)", (c) => c.notNull()).addColumn("base_url", "varchar(500)", (c) => c.notNull()).addColumn("access_token_reference", "varchar(200)", (c) => c.notNull()).addColumn("status", "varchar(32)", (c) => c.notNull()).addColumn("created_at", "varchar(40)", (c) => c.notNull()).addColumn("updated_at", "varchar(40)", (c) => c.notNull()).execute();
    await database.schema.createTable("orship_deployment_targets").ifNotExists().addColumn("id", "varchar(36)", (c) => c.primaryKey()).addColumn("provider_id", "varchar(36)", (c) => c.notNull()).addColumn("name", "varchar(160)", (c) => c.notNull()).addColumn("provider_target_id", "varchar(160)", (c) => c.notNull()).addColumn("address", "varchar(500)", (c) => c.notNull()).addColumn("production", "integer", (c) => c.notNull()).addColumn("status", "varchar(64)", (c) => c.notNull()).addColumn("created_at", "varchar(40)", (c) => c.notNull()).addColumn("updated_at", "varchar(40)", (c) => c.notNull()).execute();
    await database.schema.createTable("orship_deployment_applications").ifNotExists().addColumn("id", "varchar(36)", (c) => c.primaryKey()).addColumn("target_id", "varchar(36)", (c) => c.notNull()).addColumn("name", "varchar(160)", (c) => c.notNull()).addColumn("source_type", "varchar(32)", (c) => c.notNull()).addColumn("source_json", "text", (c) => c.notNull()).addColumn("provider_application_id", "varchar(160)", (c) => c.notNull()).addColumn("status", "varchar(64)", (c) => c.notNull()).addColumn("created_at", "varchar(40)", (c) => c.notNull()).addColumn("updated_at", "varchar(40)", (c) => c.notNull()).execute();
    await database.schema.createTable("orship_application_environments").ifNotExists().addColumn("id", "varchar(36)", (c) => c.primaryKey()).addColumn("application_id", "varchar(36)", (c) => c.notNull()).addColumn("name", "varchar(120)", (c) => c.notNull()).addColumn("variables_json", "text", (c) => c.notNull()).addColumn("created_at", "varchar(40)", (c) => c.notNull()).addColumn("updated_at", "varchar(40)", (c) => c.notNull()).execute();
    await database.schema.createTable("orship_deployments").ifNotExists().addColumn("id", "varchar(36)", (c) => c.primaryKey()).addColumn("application_id", "varchar(36)", (c) => c.notNull()).addColumn("target_id", "varchar(36)", (c) => c.notNull()).addColumn("operation", "varchar(32)", (c) => c.notNull()).addColumn("status", "varchar(32)", (c) => c.notNull()).addColumn("provider_deployment_id", "varchar(160)").addColumn("rollback_of", "varchar(36)").addColumn("actor_id", "varchar(120)", (c) => c.notNull()).addColumn("correlation_id", "varchar(36)", (c) => c.notNull()).addColumn("message", "text").addColumn("created_at", "varchar(40)", (c) => c.notNull()).addColumn("updated_at", "varchar(40)", (c) => c.notNull()).execute();
    await database.schema.createTable("orship_deployment_events").ifNotExists().addColumn("id", "integer", (c) => c.primaryKey().autoIncrement()).addColumn("deployment_id", "varchar(36)", (c) => c.notNull()).addColumn("event_type", "varchar(64)", (c) => c.notNull()).addColumn("message", "text", (c) => c.notNull()).addColumn("outcome", "varchar(32)", (c) => c.notNull()).addColumn("actor_id", "varchar(120)", (c) => c.notNull()).addColumn("correlation_id", "varchar(36)", (c) => c.notNull()).addColumn("occurred_at", "varchar(40)", (c) => c.notNull()).execute();
    await database.schema.createTable("orship_deployment_logs").ifNotExists().addColumn("id", "integer", (c) => c.primaryKey().autoIncrement()).addColumn("deployment_id", "varchar(36)", (c) => c.notNull()).addColumn("provider_log_reference", "varchar(160)").addColumn("line_count", "integer", (c) => c.notNull()).addColumn("last_seen_at", "varchar(40)", (c) => c.notNull()).execute();
    await database.schema.createTable("orship_rollback_references").ifNotExists().addColumn("id", "varchar(36)", (c) => c.primaryKey()).addColumn("deployment_id", "varchar(36)", (c) => c.notNull()).addColumn("source_deployment_id", "varchar(36)", (c) => c.notNull()).addColumn("provider_rollback_id", "varchar(160)", (c) => c.notNull()).addColumn("created_at", "varchar(40)", (c) => c.notNull()).execute();
    await database.schema.createTable("orship_health_results").ifNotExists().addColumn("id", "integer", (c) => c.primaryKey().autoIncrement()).addColumn("target_id", "varchar(36)", (c) => c.notNull()).addColumn("application_id", "varchar(36)").addColumn("status", "varchar(32)", (c) => c.notNull()).addColumn("summary", "text", (c) => c.notNull()).addColumn("checked_at", "varchar(40)", (c) => c.notNull()).addColumn("correlation_id", "varchar(36)", (c) => c.notNull()).execute();
    await database.schema.createTable("orship_deployment_audit_events").ifNotExists().addColumn("id", "varchar(36)", (c) => c.primaryKey()).addColumn("actor_id", "varchar(120)", (c) => c.notNull()).addColumn("target_id", "varchar(36)").addColumn("application_id", "varchar(36)").addColumn("operation", "varchar(64)", (c) => c.notNull()).addColumn("result", "varchar(32)", (c) => c.notNull()).addColumn("correlation_id", "varchar(36)", (c) => c.notNull()).addColumn("occurred_at", "varchar(40)", (c) => c.notNull()).execute();
  },
};

export class DeploymentStore {
  private readonly database: Database;
  constructor(private readonly dataProvider: KyselyDataProvider<DeploymentDatabase>) { this.database = dataProvider.queryDatabase(); }

  async initialize(): Promise<void> { await new MigrationRunner(this.database).run({ moduleId: "orship.deployments", migrations: [migration], seeders: [] }); }
  async close(): Promise<void> { await this.dataProvider.destroy(); }
  async registerProvider(input: ProviderSummary): Promise<void> { const now = new Date().toISOString(); await this.database.insertInto("orship_deployment_providers").values({ id: input.id, name: input.name, kind: input.kind, access_token_reference: input.accessTokenReference, base_url: input.baseUrl, status: input.status, created_at: now, updated_at: now }).onDuplicateKeyUpdate({ name: input.name, status: input.status, base_url: input.baseUrl, access_token_reference: input.accessTokenReference, updated_at: now }).execute(); }
  async listProviders(): Promise<ProviderSummary[]> { return (await this.database.selectFrom("orship_deployment_providers").selectAll().orderBy("created_at").execute()).map(toProvider); }
  async provider(id: string): Promise<ProviderSummary | undefined> { const row = await this.database.selectFrom("orship_deployment_providers").selectAll().where("id", "=", id).executeTakeFirst(); return row ? toProvider(row) : undefined; }
  async saveTarget(providerId: string, target: DeploymentTarget): Promise<void> { const now = new Date().toISOString(); await this.database.insertInto("orship_deployment_targets").values({ id: target.id, provider_id: providerId, name: target.name, provider_target_id: target.providerTargetId, address: target.address, production: target.production ? 1 : 0, status: target.status, created_at: now, updated_at: now }).onDuplicateKeyUpdate({ name: target.name, address: target.address, production: target.production ? 1 : 0, status: target.status, updated_at: now }).execute(); }
  async listTargets(): Promise<DeploymentTarget[]> { return (await this.database.selectFrom("orship_deployment_targets").selectAll().orderBy("created_at").execute()).map(toTarget); }
  async target(id: string): Promise<DeploymentTarget | undefined> { const row = await this.database.selectFrom("orship_deployment_targets").selectAll().where("id", "=", id).executeTakeFirst(); return row ? toTarget(row) : undefined; }
  async saveApplication(input: { readonly id: string; readonly targetId: string; readonly name: string; readonly source: ApplicationSource; readonly providerApplicationId: string; readonly status: string }): Promise<void> { const now = new Date().toISOString(); await this.database.insertInto("orship_deployment_applications").values({ id: input.id, target_id: input.targetId, name: input.name, source_type: input.source.type, source_json: JSON.stringify(input.source), provider_application_id: input.providerApplicationId, status: input.status, created_at: now, updated_at: now }).onDuplicateKeyUpdate({ name: input.name, source_type: input.source.type, source_json: JSON.stringify(input.source), status: input.status, updated_at: now }).execute(); }
  async application(id: string): Promise<ApplicationRow | undefined> { return this.database.selectFrom("orship_deployment_applications").selectAll().where("id", "=", id).executeTakeFirst(); }
  async listApplications(): Promise<ApplicationRow[]> { return this.database.selectFrom("orship_deployment_applications").selectAll().orderBy("created_at").execute(); }
  async saveEnvironment(applicationId: string, name: string, variables: readonly EnvironmentVariable[]): Promise<void> { const now = new Date().toISOString(); const references = variables.map(({ name: variableName, secretReference, value }) => ({ name: variableName, secretReference, hasValue: value !== undefined })); await this.database.insertInto("orship_application_environments").values({ id: randomUUID(), application_id: applicationId, name, variables_json: JSON.stringify(references), created_at: now, updated_at: now }).execute(); }
  async listEnvironments(applicationId: string): Promise<Array<{ readonly id: string; readonly name: string; readonly variables: readonly { readonly name: string; readonly secretReference?: string; readonly hasValue: boolean }[] }>> { const rows = await this.database.selectFrom("orship_application_environments").selectAll().where("application_id", "=", applicationId).orderBy("created_at").execute(); return rows.map((row) => ({ id: row.id, name: row.name, variables: JSON.parse(row.variables_json) as Array<{ name: string; secretReference?: string; hasValue: boolean }> })); }
  async createDeployment(input: Omit<DeploymentRecord, "id"> & { readonly actorId: string; readonly correlationId: string; readonly rollbackOf?: string }): Promise<DeploymentRecord> { const id = randomUUID(); const now = new Date().toISOString(); await this.database.insertInto("orship_deployments").values({ id, application_id: input.applicationId, target_id: input.targetId, operation: input.operation, status: input.status, provider_deployment_id: input.providerDeploymentId ?? null, rollback_of: input.rollbackOf ?? null, actor_id: input.actorId, correlation_id: input.correlationId, message: input.message ?? null, created_at: now, updated_at: now }).execute(); await this.recordEvent(id, input.operation, input.message ?? "Deployment requested.", "success", input.actorId, input.correlationId); return { id, ...input }; }
  async listDeployments(applicationId?: string): Promise<DeploymentRecord[]> { const query = this.database.selectFrom("orship_deployments").selectAll().orderBy("created_at desc"); const rows = applicationId ? await query.where("application_id", "=", applicationId).execute() : await query.execute(); return rows.map(toDeployment); }
  async deployment(id: string): Promise<DeploymentRow | undefined> { return this.database.selectFrom("orship_deployments").selectAll().where("id", "=", id).executeTakeFirst(); }
  async recordEvent(deploymentId: string, eventType: string, message: string, outcome: string, actorId: string, correlationId: string): Promise<void> { await this.database.insertInto("orship_deployment_events").values({ deployment_id: deploymentId, event_type: eventType, message: redact(message), outcome, actor_id: actorId, correlation_id: correlationId, occurred_at: new Date().toISOString() }).execute(); }
  async recordAudit(input: { readonly actorId: string; readonly targetId?: string; readonly applicationId?: string; readonly operation: string; readonly result: string; readonly correlationId: string }): Promise<void> { await this.database.insertInto("orship_deployment_audit_events").values({ id: randomUUID(), actor_id: input.actorId, target_id: input.targetId ?? null, application_id: input.applicationId ?? null, operation: input.operation, result: input.result, correlation_id: input.correlationId, occurred_at: new Date().toISOString() }).execute(); }
  async recordHealth(targetId: string, applicationId: string | undefined, status: string, summary: string, correlationId: string): Promise<void> { await this.database.insertInto("orship_health_results").values({ target_id: targetId, application_id: applicationId ?? null, status, summary: redact(summary), checked_at: new Date().toISOString(), correlation_id: correlationId }).execute(); }
}

function toProvider(row: ProviderRow): ProviderSummary { return { id: row.id, name: row.name, kind: row.kind as DeploymentProviderKind, baseUrl: row.base_url, accessTokenReference: row.access_token_reference, status: row.status as ProviderSummary["status"] }; }
function toTarget(row: TargetRow): DeploymentTarget { return { id: row.id, name: row.name, address: row.address, production: Boolean(row.production), providerTargetId: row.provider_target_id, status: row.status }; }
function toDeployment(row: DeploymentRow): DeploymentRecord { return { id: row.id, applicationId: row.application_id, targetId: row.target_id, operation: row.operation as DeploymentOperation, status: row.status, providerDeploymentId: row.provider_deployment_id ?? undefined, message: row.message ?? undefined }; }
function redact(value: string): string { return value.replace(/(password|token|secret|private[_ -]?key)\s*[:=]\s*[^\s,;]+/giu, "$1=[redacted]"); }
