import { randomUUID } from "node:crypto";
import type { FastifyInstance, FastifyReply, FastifyRequest } from "fastify";
import { EnvironmentSecretProvider, type LocalIdentityStore } from "@codexsun/platform-core";
import { z } from "zod";
import { DokployProvider } from "./dokploy-adapter.js";
import { DeploymentProviderError, type DeploymentApplication, type DeploymentProvider, type ProviderRegistrationInput } from "./provider.js";
import { DeploymentStore, type DeploymentApplicationRow } from "./deployment-store.js";

const providerInputSchema = z.object({ name: z.string().trim().min(1).max(160), kind: z.literal("dokploy"), baseUrl: z.string().url().optional(), accessTokenReference: z.string().trim().min(1).max(200).optional() });
const sourceSchema = z.object({ type: z.enum(["docker", "compose", "git"]), repository: z.string().max(500).optional(), branch: z.string().max(160).optional(), image: z.string().max(500).optional(), composeFile: z.string().max(200_000).optional() });
const applicationInputSchema = z.object({ name: z.string().trim().min(1).max(160), targetId: z.string().uuid(), source: sourceSchema });
const environmentSchema = z.object({ name: z.string().trim().min(1).max(120), variables: z.array(z.object({ name: z.string().trim().min(1).max(160), value: z.string().max(10_000).optional(), secretReference: z.string().trim().max(200).optional() }).refine((item) => item.value === undefined || item.secretReference === undefined, "Use a value or secret reference, not both.")).max(500) });
const deploymentInputSchema = z.object({ applicationId: z.string().uuid(), operation: z.enum(["deploy", "redeploy", "stop", "start", "rollback"]), providerRollbackId: z.string().max(160).optional() });
const idParams = z.object({ id: z.string().uuid() });
const errorSchema = z.object({ error: z.string(), code: z.string().optional() });
const deploymentResponseSchema = { 200: z.unknown(), 201: z.unknown(), 400: errorSchema, 401: errorSchema, 403: errorSchema, 404: errorSchema, 429: errorSchema, 502: errorSchema };
const actionWindows = new Map<string, { count: number; startedAt: number }>();

type DeploymentRoutesOptions = {
  readonly identity: LocalIdentityStore;
  readonly store: DeploymentStore;
  readonly dokployBaseUrl?: string;
  readonly secretProvider?: EnvironmentSecretProvider;
  readonly dokployAccessTokenReference: string;
};

export async function registerDeploymentRoutes(app: FastifyInstance, options: DeploymentRoutesOptions): Promise<void> {
  const secretProvider = options.secretProvider ?? new EnvironmentSecretProvider({ [options.dokployAccessTokenReference]: options.dokployAccessTokenReference });
  const actor = (request: FastifyRequest, reply: FastifyReply, permission: string) => {
    const authenticated = options.identity.authenticate(request.headers.authorization, request.headers["x-codexsun-browser-session"]);
    if (!authenticated) { reply.code(401).send({ error: "Authentication required.", code: "auth.required" }); return undefined; }
    if (!authenticated.permissions.includes("*") && !authenticated.permissions.includes(permission)) { reply.code(403).send({ error: `Permission required: ${permission}.`, code: "auth.forbidden" }); return undefined; }
    return authenticated;
  };
  const providerFor = async (providerId: string): Promise<DeploymentProvider> => {
    const record = await options.store.provider(providerId);
    if (!record) throw new DeploymentProviderError("provider.not_found", "Deployment provider was not found.", false);
    return new DokployProvider({ ...record, secretProvider });
  };

  app.get("/api/v1/orship/deployment/providers", { schema: { response: deploymentResponseSchema } }, async (request, reply) => { if (!actor(request, reply, "providers.read")) return; return { providers: await options.store.listProviders() }; });
  app.post("/api/v1/orship/deployment/providers", { schema: { body: providerInputSchema, response: deploymentResponseSchema } }, async (request, reply) => {
    const authenticated = actor(request, reply, "providers.manage"); if (!authenticated) return; if (!allowAction(authenticated.id, request.url)) return reply.code(429).send({ error: "Too many deployment actions. Try again later.", code: "deployment.rate_limited" });
    const input = providerInputSchema.parse(request.body); const baseUrl = input.baseUrl ?? options.dokployBaseUrl; if (!baseUrl) return reply.code(400).send({ error: "A configured Dokploy base URL is required.", code: "provider.url_required" });
    const record: ProviderRegistrationInput = { name: input.name, kind: input.kind, baseUrl, accessTokenReference: input.accessTokenReference ?? options.dokployAccessTokenReference }; const provider = new DokployProvider({ ...record, id: randomUUID(), secretProvider }); const correlationId = correlation(request);
    try { const summary = await provider.registerProvider(record); await options.store.registerProvider(summary); await options.store.recordAudit({ actorId: authenticated.id, operation: "provider.register", result: "success", correlationId }); return reply.code(201).send({ provider: summary }); } catch (error) { await options.store.recordAudit({ actorId: authenticated.id, operation: "provider.register", result: "failure", correlationId }); return providerError(reply, error); }
  });
  app.get("/api/v1/orship/deployment/providers/:id/health", { schema: { params: idParams, response: deploymentResponseSchema } }, async (request, reply) => { if (!actor(request, reply, "health.read")) return; const params = idParams.parse(request.params); try { const result = await (await providerFor(params.id)).healthCheck(); return result; } catch (error) { return providerError(reply, error); } });

  app.get("/api/v1/orship/deployment/targets", { schema: { response: deploymentResponseSchema } }, async (request, reply) => { if (!actor(request, reply, "targets.read")) return; return { targets: await options.store.listTargets() }; });
  app.post("/api/v1/orship/deployment/targets/sync", { schema: { response: deploymentResponseSchema } }, async (request, reply) => {
    const authenticated = actor(request, reply, "targets.manage"); if (!authenticated) return; if (!allowAction(authenticated.id, request.url)) return reply.code(429).send({ error: "Too many deployment actions. Try again later.", code: "deployment.rate_limited" }); const providerRecord = (await options.store.listProviders())[0]; if (!providerRecord) return reply.code(400).send({ error: "Register a deployment provider first.", code: "provider.required" }); const correlationId = correlation(request);
    try { const provider = await providerFor(providerRecord.id); const targets = await provider.listTargets(); for (const target of targets) await options.store.saveTarget(providerRecord.id, target); await options.store.recordAudit({ actorId: authenticated.id, operation: "target.sync", result: "success", correlationId }); return { targets: await options.store.listTargets() }; } catch (error) { await options.store.recordAudit({ actorId: authenticated.id, operation: "target.sync", result: "failure", correlationId }); return providerError(reply, error); }
  });
  app.get("/api/v1/orship/deployment/targets/:id/health", { schema: { params: idParams, response: deploymentResponseSchema } }, async (request, reply) => {
    if (!actor(request, reply, "health.read")) return; const params = idParams.parse(request.params); const target = await options.store.target(params.id); if (!target) return reply.code(404).send({ error: "Deployment target was not found.", code: "target.not_found" }); const providers = await options.store.listProviders(); const providerRecord = providers[0]; if (!providerRecord) return reply.code(400).send({ error: "Register a deployment provider first.", code: "provider.required" }); try { const result = await (await providerFor(providerRecord.id)).testTarget(target); await options.store.recordHealth(target.id, undefined, result.status, result.message, correlation(request)); return result; } catch (error) { return providerError(reply, error); }
  });

  app.get("/api/v1/orship/deployment/applications", { schema: { response: deploymentResponseSchema } }, async (request, reply) => { if (!actor(request, reply, "applications.read")) return; return { applications: await options.store.listApplications() }; });
  app.post("/api/v1/orship/deployment/applications", { schema: { body: applicationInputSchema, response: deploymentResponseSchema } }, async (request, reply) => {
    const authenticated = actor(request, reply, "applications.manage"); if (!authenticated) return; const input = applicationInputSchema.parse(request.body); const target = await options.store.target(input.targetId); if (!target) return reply.code(404).send({ error: "Deployment target was not found.", code: "target.not_found" }); const providerRecord = (await options.store.listProviders())[0]; if (!providerRecord) return reply.code(400).send({ error: "Register a deployment provider first.", code: "provider.required" }); const correlationId = correlation(request);
    try { const application = await (await providerFor(providerRecord.id)).createApplication({ ...input, target }); await options.store.saveApplication(application); await options.store.recordAudit({ actorId: authenticated.id, targetId: target.id, applicationId: application.id, operation: "application.create", result: "success", correlationId }); return reply.code(201).send({ application: safeApplication(application) }); } catch (error) { await options.store.recordAudit({ actorId: authenticated.id, targetId: target.id, operation: "application.create", result: "failure", correlationId }); return providerError(reply, error); }
  });
  app.get("/api/v1/orship/deployment/applications/:id/environments", { schema: { params: idParams, response: deploymentResponseSchema } }, async (request, reply) => { if (!actor(request, reply, "applications.read")) return; const params = idParams.parse(request.params); return { environments: await options.store.listEnvironments(params.id) }; });
  app.post("/api/v1/orship/deployment/applications/:id/environments", { schema: { params: idParams, body: environmentSchema, response: deploymentResponseSchema } }, async (request, reply) => {
    const params = idParams.parse(request.params); const authenticated = actor(request, reply, "applications.manage"); if (!authenticated) return; if (!allowAction(authenticated.id, request.url)) return reply.code(429).send({ error: "Too many deployment actions. Try again later.", code: "deployment.rate_limited" }); const application = await options.store.application(params.id); if (!application) return reply.code(404).send({ error: "Application was not found.", code: "application.not_found" }); const input = environmentSchema.parse(request.body); const target = await options.store.target(application.target_id); const providerRecord = (await options.store.listProviders())[0]; if (!target || !providerRecord) return reply.code(400).send({ error: "Application provider target is unavailable.", code: "target.unavailable" }); const correlationId = correlation(request); try { const provider = await providerFor(providerRecord.id); const deploymentApplication = applicationFromRow(application); await provider.setEnvironment(deploymentApplication, input.variables); await options.store.saveEnvironment(application.id, input.name, input.variables); await options.store.recordAudit({ actorId: authenticated.id, targetId: target.id, applicationId: application.id, operation: "environment.update", result: "success", correlationId }); return reply.code(201).send({ environment: { name: input.name, variables: input.variables.map((item) => ({ name: item.name, secretReference: item.secretReference, hasValue: item.value !== undefined })) } }); } catch (error) { await options.store.recordAudit({ actorId: authenticated.id, targetId: target.id, applicationId: application.id, operation: "environment.update", result: "failure", correlationId }); return providerError(reply, error); }
  });

  app.get("/api/v1/orship/deployment/deployments", { schema: { response: deploymentResponseSchema } }, async (request, reply) => { if (!actor(request, reply, "deployments.read")) return; return { deployments: await options.store.listDeployments() }; });
  app.post("/api/v1/orship/deployment/deployments", { schema: { body: deploymentInputSchema, response: deploymentResponseSchema } }, async (request, reply) => {
    const input = deploymentInputSchema.parse(request.body); const permission = input.operation === "rollback" ? "deployments.rollback" : "deployments.create"; const authenticated = actor(request, reply, permission); if (!authenticated) return; if (!allowAction(authenticated.id, request.url)) return reply.code(429).send({ error: "Too many deployment actions. Try again later.", code: "deployment.rate_limited" }); const application = await options.store.application(input.applicationId); if (!application) return reply.code(404).send({ error: "Application was not found.", code: "application.not_found" }); const target = await options.store.target(application.target_id); const providerRecord = (await options.store.listProviders())[0]; if (!target || !providerRecord) return reply.code(400).send({ error: "Application deployment target is unavailable.", code: "target.unavailable" }); const correlationId = correlation(request); try { const provider = await providerFor(providerRecord.id); const deploymentApplication = applicationFromRow(application); const result = input.operation === "deploy" ? await provider.deployApplication(deploymentApplication) : input.operation === "redeploy" ? await provider.redeployApplication(deploymentApplication) : input.operation === "stop" ? await provider.stopApplication(deploymentApplication) : input.operation === "start" ? await provider.startApplication(deploymentApplication) : await provider.rollbackApplication(deploymentApplication, input.providerRollbackId ?? ""); const deployment = await options.store.createDeployment({ ...result, actorId: authenticated.id, correlationId }); await options.store.recordAudit({ actorId: authenticated.id, targetId: target.id, applicationId: application.id, operation: `deployment.${input.operation}`, result: "success", correlationId }); return reply.code(201).send({ deployment }); } catch (error) { await options.store.recordAudit({ actorId: authenticated.id, targetId: target.id, applicationId: application.id, operation: `deployment.${input.operation}`, result: "failure", correlationId }); return providerError(reply, error); }
  });
  app.get("/api/v1/orship/deployment/deployments/:id/logs", { schema: { params: idParams, querystring: z.object({ tail: z.coerce.number().int().min(1).max(10_000).default(100) }), response: deploymentResponseSchema } }, async (request, reply) => { if (!actor(request, reply, "logs.read")) return; const params = idParams.parse(request.params); const query = z.object({ tail: z.coerce.number().int().min(1).max(10_000).default(100) }).parse(request.query); const deployment = await options.store.deployment(params.id); if (!deployment?.provider_deployment_id) return reply.code(404).send({ error: "Provider deployment logs are not available.", code: "logs.not_found" }); const application = await options.store.application(deployment.application_id); const providers = await options.store.listProviders(); if (!application || !providers[0]) return reply.code(404).send({ error: "Deployment application was not found.", code: "application.not_found" }); try { const logs = await (await providerFor(providers[0].id)).getDeploymentLogs(applicationFromRow(application), deployment.provider_deployment_id, query.tail); return { logs }; } catch (error) { return providerError(reply, error); } });
}

function applicationFromRow(row: DeploymentApplicationRow): DeploymentApplication { return { id: row.id, name: row.name, source: JSON.parse(row.source_json) as DeploymentApplication["source"], targetId: row.target_id, providerApplicationId: row.provider_application_id, status: row.status }; }
function safeApplication(application: DeploymentApplication): DeploymentApplication { return application; }
function correlation(request: FastifyRequest): string { return typeof request.headers["x-correlation-id"] === "string" && /^[a-z0-9-]{8,64}$/iu.test(request.headers["x-correlation-id"]) ? request.headers["x-correlation-id"] : randomUUID(); }
function providerError(reply: FastifyReply, error: unknown) { if (error instanceof DeploymentProviderError) return reply.code(error.retryable ? 502 : 400).send({ error: error.message, code: error.code }); return reply.code(502).send({ error: "Deployment provider request failed.", code: "provider.failed" }); }
function allowAction(actorId: string, operation: string): boolean { const now = Date.now(); const key = `${actorId}:${operation}`; const current = actionWindows.get(key); if (!current || now - current.startedAt >= 60_000) { actionWindows.set(key, { count: 1, startedAt: now }); return true; } if (current.count >= 20) return false; current.count += 1; return true; }
