export const featuredCardSampleItems = [
  {
    id: "featured-card-01",
    href: "/catalog",
    name: "Summer Cotton Kurta Set",
    imageUrl: "https://placehold.co/900x1200/f0e1d2/2d211b?text=Kurta",
    badge: "Featured",
    brandName: "Aarohi",
    categoryName: "Women",
    shortDescription: "Light festive styling with breathable cotton texture.",
    amount: 1999,
    compareAtAmount: 2599,
    availableQuantity: 12,
  },
  {
    id: "featured-card-02",
    href: "/catalog",
    name: "Minimal Leather Tote",
    imageUrl: "https://placehold.co/900x1200/e7ddd5/2d211b?text=Tote",
    badge: "New",
    brandName: "Mysa",
    categoryName: "Accessories",
    shortDescription: "Clean structure for daily carry with subtle contrast trim.",
    amount: 2499,
    compareAtAmount: 2999,
    availableQuantity: 9,
  },
  {
    id: "featured-card-03",
    href: "/catalog",
    name: "Classic Layered Watch",
    imageUrl: "https://placehold.co/900x1200/efe6dc/2d211b?text=Watch",
    badge: "Top pick",
    brandName: "Noir",
    categoryName: "Watches",
    shortDescription: "Refined metallic case with modern day-to-night appeal.",
    amount: 3299,
    compareAtAmount: 3899,
    availableQuantity: 6,
  },
  {
    id: "featured-card-04",
    href: "/catalog",
    name: "Weekend Sneaker Edit",
    imageUrl: "https://placehold.co/900x1200/e8ddd1/2d211b?text=Sneaker",
    badge: "Fresh",
    brandName: "Stride",
    categoryName: "Footwear",
    shortDescription: "Soft neutral palette made for everyday movement.",
    amount: 2799,
    compareAtAmount: 3199,
    availableQuantity: 14,
  },
  {
    id: "featured-card-05",
    href: "/catalog",
    name: "Tailored Relaxed Shirt",
    imageUrl: "https://placehold.co/900x1200/f3e8dc/2d211b?text=Shirt",
    badge: "Editor",
    brandName: "Studio 08",
    categoryName: "Men",
    shortDescription: "Relaxed fit with sharp collar balance and soft drape.",
    amount: 1699,
    compareAtAmount: 2199,
    availableQuantity: 8,
  },
  {
    id: "featured-card-06",
    href: "/catalog",
    name: "Gift Box Essentials",
    imageUrl: "https://placehold.co/900x1200/ede1d4/2d211b?text=Gift",
    badge: "Bundle",
    brandName: "Maison",
    categoryName: "Gifting",
    shortDescription: "Curated set of small luxuries packed for quick gifting.",
    amount: 1499,
    compareAtAmount: 1899,
    availableQuantity: 5,
  },
]
