import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import type { ReactNode } from "react";
import { Badge } from "@codexsun/ui/components/badge";
import { Button } from "@codexsun/ui/components/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@codexsun/ui/components/card";
import { Input } from "@codexsun/ui/components/input";
import { FileTextIcon, RefreshCwIcon, RocketIcon, RotateCcwIcon, SaveIcon, ShieldCheckIcon } from "lucide-react";
import { useState } from "react";
import { checkProviderHealth, createApplication, createDeployment, createProvider, fetchApplicationEnvironments, fetchApplications, fetchDeploymentLogs, fetchDeployments, fetchProviders, fetchTargets, saveEnvironment, syncTargets, type Application, type Deployment } from "./deployments-api";

export type DeploymentPage = "overview" | "providers" | "targets" | "applications" | "application" | "history" | "logs" | "health" | "access-denied";

export function DeploymentWorkspace({ request, page, applicationId, onNavigate }: { request: typeof fetch; page: DeploymentPage; applicationId?: string; onNavigate: (page: DeploymentPage, id?: string) => void }) {
  const providers = useQuery({ queryKey: ["orship", "deployments", "providers"], queryFn: () => fetchProviders(request), refetchInterval: 15_000 });
  const targets = useQuery({ queryKey: ["orship", "deployments", "targets"], queryFn: () => fetchTargets(request), refetchInterval: 10_000 });
  const applications = useQuery({ queryKey: ["orship", "deployments", "applications"], queryFn: () => fetchApplications(request), refetchInterval: 10_000 });
  const deployments = useQuery({ queryKey: ["orship", "deployments", "history"], queryFn: () => fetchDeployments(request), refetchInterval: 10_000 });
  const sync = useMutation({ mutationFn: () => syncTargets(request), onSuccess: () => targets.refetch() });
  const title = page === "overview" ? "Deployments" : page === "access-denied" ? "Access denied" : page === "application" ? "Application details" : page[0].toUpperCase() + page.slice(1);
  const queryError = [providers, targets, applications, deployments].find((query) => query.isError)?.error;
  return <main className="size-full overflow-y-auto bg-background p-6"><section className="mx-auto flex w-full max-w-6xl flex-col gap-6"><header className="flex flex-col gap-4"><div className="flex items-end justify-between gap-4"><div><p className="text-sm font-medium text-muted-foreground">Orship deployment control plane</p><h1 className="text-2xl font-semibold tracking-tight">{title}</h1><p className="mt-2 text-sm text-muted-foreground">Provider-backed state refreshed from the Orship API.</p></div>{page === "targets" ? <Button disabled={sync.isPending} onClick={() => sync.mutate()}><RefreshCwIcon />Sync targets</Button> : null}</div><DeploymentTabs page={page} onNavigate={onNavigate} /></header>{queryError ? <ErrorState message={queryError instanceof Error ? queryError.message : "Deployment data could not be loaded."} /> : page === "overview" ? <Overview providers={providers.data?.providers ?? []} targets={targets.data?.targets ?? []} applications={applications.data?.applications ?? []} deployments={deployments.data?.deployments ?? []} onNavigate={onNavigate} /> : page === "providers" ? <Providers request={request} providers={providers.data?.providers ?? []} onCreated={() => providers.refetch()} /> : page === "targets" ? <Targets targets={targets.data?.targets ?? []} /> : page === "applications" ? <Applications request={request} applications={applications.data?.applications ?? []} targets={targets.data?.targets ?? []} onOpen={(id) => onNavigate("application", id)} onCreated={() => applications.refetch()} /> : page === "application" ? <ApplicationDetails request={request} application={applications.data?.applications.find((item) => item.id === applicationId)} /> : page === "history" ? <History deployments={deployments.data?.deployments ?? []} /> : page === "logs" ? <Logs request={request} deployments={deployments.data?.deployments ?? []} /> : page === "health" ? <Health request={request} providers={providers.data?.providers ?? []} /> : <AccessDenied />}</section></main>;
}

function DeploymentTabs({ page, onNavigate }: { page: DeploymentPage; onNavigate: (page: DeploymentPage) => void }) { const tabs: [DeploymentPage, string][] = [["overview", "Overview"], ["providers", "Providers"], ["targets", "Targets"], ["applications", "Applications"], ["history", "History"], ["logs", "Logs"], ["health", "Health"]]; return <nav className="flex flex-wrap gap-1 border-b" aria-label="Deployment views">{tabs.map(([id, label]) => <Button key={id} size="sm" variant={page === id || (id === "applications" && page === "application") ? "secondary" : "ghost"} onClick={() => onNavigate(id)}>{label}</Button>)}</nav>; }

function Overview({ providers, targets, applications, deployments, onNavigate }: { providers: unknown[]; targets: unknown[]; applications: unknown[]; deployments: unknown[]; onNavigate: (page: DeploymentPage) => void }) { return <div className="grid gap-4 md:grid-cols-2">{[["Providers", providers.length, "providers"], ["Targets", targets.length, "targets"], ["Applications", applications.length, "applications"], ["Recent deployments", deployments.length, "history"]].map(([label, value, page]) => <button className="text-left" key={String(label)} onClick={() => onNavigate(page as DeploymentPage)}><Card className="transition-colors hover:border-foreground/30"><CardHeader><CardDescription>{label}</CardDescription><CardTitle className="text-3xl">{String(value)}</CardTitle></CardHeader><CardContent className="text-sm text-muted-foreground">Live records from MariaDB and the configured provider.</CardContent></Card></button>)}</div>; }
function Providers({ request, providers, onCreated }: { request: typeof fetch; providers: { id: string; name: string; kind: string; baseUrl: string; status: string }[]; onCreated: () => void }) { const [name, setName] = useState(""); const [baseUrl, setBaseUrl] = useState(""); const [tokenReference, setTokenReference] = useState("DOKPLOY_ACCESS_TOKEN"); const mutation = useMutation({ mutationFn: () => createProvider(request, { name, baseUrl, kind: "dokploy", accessTokenReference: tokenReference }), onSuccess: () => { setName(""); setBaseUrl(""); onCreated(); } }); return <div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_minmax(0,1.5fr)]"><Card><CardHeader><CardTitle>Register provider</CardTitle><CardDescription>Connect Orship to an authenticated Dokploy API.</CardDescription></CardHeader><CardContent className="grid gap-4"><Field label="Name"><Input value={name} onChange={(event) => setName(event.target.value)} placeholder="Local Dokploy" /></Field><Field label="Base URL"><Input value={baseUrl} onChange={(event) => setBaseUrl(event.target.value)} placeholder="https://dokploy.example.com/api" /></Field><Field label="Access token reference"><Input value={tokenReference} onChange={(event) => setTokenReference(event.target.value)} /></Field><Button disabled={!name || !baseUrl || mutation.isPending} onClick={() => mutation.mutate()}><ShieldCheckIcon />Register provider</Button>{mutation.isError ? <ErrorState message={mutation.error.message} /> : null}</CardContent></Card><ListCard title="Registered providers" description="Provider values are stored as references and health is checked live.">{providers.map((provider) => <div className="flex items-center justify-between border-b py-3 last:border-0" key={provider.id}><div><p className="font-medium">{provider.name}</p><p className="text-sm text-muted-foreground">{provider.kind} · {provider.baseUrl}</p></div><HealthBadge request={request} id={provider.id} /></div>)}</ListCard></div>; }
function Targets({ targets }: { targets: { id: string; name: string; address: string; status: string; production: boolean }[] }) { return <ListCard title="Targets" description="Provider-managed remote or local deployment hosts.">{targets.length ? targets.map((target) => <div className="flex items-center justify-between border-b py-3 last:border-0" key={target.id}><div><p className="font-medium">{target.name}</p><p className="text-sm text-muted-foreground">{target.address} · {target.production ? "production" : "development"}</p></div><Badge>{target.status}</Badge></div>) : <Empty text="No targets synced. Register a provider and sync targets." />}</ListCard>; }
function Applications({ request, applications, targets, onOpen, onCreated }: { request: typeof fetch; applications: Application[]; targets: { id: string; name: string }[]; onOpen: (id: string) => void; onCreated: () => void }) { const [name, setName] = useState(""); const [targetId, setTargetId] = useState(targets[0]?.id ?? ""); const [image, setImage] = useState(""); const mutation = useMutation({ mutationFn: () => createApplication(request, { name, targetId, source: { type: "docker", image } }), onSuccess: () => { setName(""); setImage(""); onCreated(); } }); return <div className="grid gap-4"><Card><CardHeader><CardTitle>Register application</CardTitle><CardDescription>Create a Docker application in a managed target.</CardDescription></CardHeader><CardContent className="grid gap-4 md:grid-cols-3"><Field label="Application name"><Input value={name} onChange={(event) => setName(event.target.value)} placeholder="cxforge-api" /></Field><Field label="Target"><select className="h-9 rounded-md border bg-background px-3 text-sm" value={targetId} onChange={(event) => setTargetId(event.target.value)}>{targets.map((target) => <option key={target.id} value={target.id}>{target.name}</option>)}</select></Field><Field label="Docker image"><Input value={image} onChange={(event) => setImage(event.target.value)} placeholder="registry.example.com/app:latest" /></Field><div className="md:col-span-3"><Button disabled={!name || !targetId || !image || mutation.isPending} onClick={() => mutation.mutate()}><RocketIcon />Register application</Button>{mutation.isError ? <span className="ml-3 text-sm text-destructive">{mutation.error.message}</span> : null}</div></CardContent></Card><Card><CardHeader><CardTitle>Applications</CardTitle><CardDescription>Application records and deployment actions.</CardDescription></CardHeader><CardContent className="grid gap-3">{applications.length ? applications.map((application) => <ApplicationRow key={application.id} request={request} application={application} onOpen={() => onOpen(application.id)} />) : <Empty text="No applications registered." />}</CardContent></Card></div>; }
function ApplicationRow({ request, application, onOpen }: { request: typeof fetch; application: Application; onOpen: () => void }) { const queryClient = useQueryClient(); const deploy = useMutation({ mutationFn: (operation: "deploy" | "redeploy") => createDeployment(request, application.id, operation), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["orship", "deployments"] }) }); return <div className="flex flex-wrap items-center justify-between gap-3 rounded-md border p-4"><div><p className="font-medium">{application.name}</p><p className="text-sm text-muted-foreground">{application.status} · target {application.target_id}</p></div><div className="flex flex-wrap gap-2"><Button size="sm" onClick={() => deploy.mutate("deploy")} disabled={deploy.isPending}><RocketIcon />Deploy</Button><Button size="sm" variant="outline" onClick={() => deploy.mutate("redeploy")} disabled={deploy.isPending}><RotateCcwIcon />Redeploy</Button><Button size="sm" variant="outline" onClick={onOpen}><FileTextIcon />Details</Button></div></div>; }

function ApplicationDetails({ request, application }: { request: typeof fetch; application?: Application }) { const environments = useQuery({ enabled: Boolean(application), queryKey: ["orship", "deployments", "environment", application?.id], queryFn: () => fetchApplicationEnvironments(request, application!.id) }); const [name, setName] = useState("production"); const [variableName, setVariableName] = useState(""); const [secretReference, setSecretReference] = useState(""); const mutation = useMutation({ mutationFn: () => saveEnvironment(request, application!.id, { name, variables: [{ name: variableName, secretReference }] }), onSuccess: () => environments.refetch() }); if (!application) return <Empty text="Select an application to inspect its details." />; let source = application.source_json; try { source = JSON.stringify(JSON.parse(source), null, 2); } catch { /* Keep malformed provider data visible without crashing the page. */ } return <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>{application.name}</CardTitle><CardDescription>Application registry record and provider source.</CardDescription></CardHeader><CardContent className="grid gap-4"><div className="flex items-center gap-2"><Badge>{application.status}</Badge><span className="text-sm text-muted-foreground">Target {application.target_id}</span></div><pre className="max-h-64 overflow-auto rounded-md bg-muted p-3 text-xs">{source}</pre></CardContent></Card><Card><CardHeader><CardTitle>Environment</CardTitle><CardDescription>Values stay in the secret provider; only references are displayed.</CardDescription></CardHeader><CardContent className="grid gap-4"><Field label="Environment name"><Input value={name} onChange={(event) => setName(event.target.value)} /></Field><Field label="Variable name"><Input value={variableName} onChange={(event) => setVariableName(event.target.value)} placeholder="DATABASE_URL" /></Field><Field label="Secret reference"><Input value={secretReference} onChange={(event) => setSecretReference(event.target.value)} placeholder="ORSHIP_DATABASE_URL" /></Field><Button disabled={!variableName || !secretReference || mutation.isPending} onClick={() => mutation.mutate()}><SaveIcon />Save reference</Button>{mutation.isError ? <ErrorState message={mutation.error.message} /> : null}<div className="border-t pt-3 text-sm text-muted-foreground">{environments.isPending ? "Loading environments..." : `Stored environments: ${environments.data?.environments.length ?? 0}`}</div></CardContent></Card></div>; }
function History({ deployments }: { deployments: Deployment[] }) { return <ListCard title="Deployment history" description="Audited operations recorded by Orship.">{deployments.map((deployment) => <div className="flex items-center justify-between border-b py-3 last:border-0" key={deployment.id}><div><p className="font-medium">{deployment.operation} · {deployment.application_id}</p><p className="text-sm text-muted-foreground">{deployment.created_at ?? "recent"}</p></div><Badge>{deployment.status}</Badge></div>)}</ListCard>; }
function Logs({ request, deployments }: { request: typeof fetch; deployments: Deployment[] }) { const deployment = deployments[0]; const logs = useQuery({ enabled: Boolean(deployment), queryKey: ["orship", "deployments", "logs", deployment?.id], queryFn: () => fetchDeploymentLogs(request, deployment!.id), refetchInterval: 5_000 }); return <ListCard title="Deployment logs" description="Provider logs are fetched through Orship and redacted at the boundary.">{!deployment ? <Empty text="No deployment logs are available." /> : logs.isPending ? <p className="text-sm text-muted-foreground">Loading logs...</p> : logs.data?.logs.map((log, index) => <pre className="border-b py-2 text-xs last:border-0" key={`${index}-${log.timestamp}`}>{log.message}</pre>)}</ListCard>; }
function Health({ request, providers }: { request: typeof fetch; providers: { id: string; name: string }[] }) { return <ListCard title="Health" description="Live connectivity checks for deployment providers.">{providers.map((provider) => <div key={provider.id}><p className="font-medium">{provider.name}</p><HealthBadge request={request} id={provider.id} /></div>)}</ListCard>; }
function HealthBadge({ request, id }: { request: typeof fetch; id: string }) { const health = useQuery({ queryKey: ["orship", "deployments", "health", id], queryFn: () => checkProviderHealth(request, id), refetchInterval: 15_000 }); return <Badge variant={health.data?.status === "healthy" ? "default" : "outline"}>{health.isPending ? "checking" : health.data?.status ?? "unavailable"}</Badge>; }
function ListCard({ title, description, children }: { title: string; description: string; children: ReactNode }) { return <Card><CardHeader><CardTitle>{title}</CardTitle><CardDescription>{description}</CardDescription></CardHeader><CardContent>{children || <Empty text="No records yet." />}</CardContent></Card>; }
function Empty({ text }: { text: string }) { return <p className="text-sm text-muted-foreground">{text}</p>; }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="grid gap-2 text-sm font-medium"><span>{label}</span>{children}</label>; }
function ErrorState({ message }: { message: string }) { return <p className="text-sm text-destructive" role="alert">{message}</p>; }
function AccessDenied() { return <Card><CardHeader><CardTitle>Access denied</CardTitle><CardDescription>Your identity is authenticated, but it does not have the deployment permission required for this view.</CardDescription></CardHeader><CardContent className="text-sm text-muted-foreground">Ask an Orship administrator for the appropriate providers, targets, applications, deployments, logs, or health permission.</CardContent></Card>; }
