/**
 * Integration Examples for Orexso and Agentic Tools
 *
 * Shows practical usage patterns for the CodeAssist agent.
 */

import {
  createAgenticTools,
  quickWorkflow,
  streamPlanning,
} from "./agentic-tools.js";
import { createOrexsoClient } from "./orexso-client.js";

/**
 * Example 1: Simple Chat Request
 */
export async function example1_simpleChat() {
  console.log("Example 1: Simple Chat Request\n");

  const client = createOrexsoClient({
    baseUrl: "http://localhost:6005",
  });

  try {
    const health = await client.getHealth();
    console.log("Orexso Status:", health.status);
    console.log("Model:", health.chat_model);

    const response = await client.chat({
      message: "Explain the repository structure briefly",
      session_id: "example-1",
      use_model: true,
      history: [],
    });

    console.log("\nAssistant:", response.reply);
    console.log("Generated by:", response.generated_by);
    console.log("Activities:", response.activities.length);
  } catch (error) {
    console.error("Error:", error);
  }
}

/**
 * Example 2: Streaming Chat with Partial Tokens
 */
export async function example2_streamingChat() {
  console.log("Example 2: Streaming Chat\n");

  const client = createOrexsoClient({
    baseUrl: "http://localhost:6005",
  });

  try {
    let fullText = "";

    for await (const event of client.stream({
      message: "How would you implement a TypeScript function to parse JSON safely?",
      session_id: "example-2",
      use_model: true,
      history: [],
    })) {
      if (event.type === "chunk") {
        const data = event.data as Record<string, string>;
        const chunk = data.content || "";
        process.stdout.write(chunk);
        fullText += chunk;
      }

      if (event.type === "metadata") {
        const meta = event.data as Record<string, unknown>;
        console.log("\n\n[Task ID:", meta.task_id, "]");
      }

      if (event.type === "done") {
        console.log("\n[Streaming Complete]");
      }
    }
  } catch (error) {
    console.error("Error:", error);
  }
}

/**
 * Example 3: Using Agentic Tools - Planning
 */
export async function example3_planning() {
  console.log("Example 3: Code Planning\n");

  const tools = createAgenticTools(undefined, {
    projectId: "default",
    sessionId: "example-3",
    activeFile: "src/app.ts",
  });

  try {
    const plan = await tools.plan(
      "Create a utility function to validate email addresses with comprehensive regex and additional checks"
    );

    console.log("Task ID:", plan.taskId);
    console.log("Summary:", plan.summary);
    console.log("\nDiscovered Files:");
    plan.discoveredFiles.forEach((file: string) => console.log("  -", file));
    console.log("\nPlan:");
    console.log("  Assumptions:");
    plan.plan.assumptions.forEach((assumption: string) =>
      console.log("    -", assumption)
    );
    console.log("  Steps:");
    plan.plan.steps.forEach((step, index) =>
      console.log(`    ${index + 1}. ${step.description}`)
    );
  } catch (error) {
    console.error("Error:", error);
  }
}

/**
 * Example 4: Using Agentic Tools - Writing Code
 */
export async function example4_writeCode() {
  console.log("Example 4: Code Writing (No Changes Applied)\n");

  const tools = createAgenticTools(undefined, {
    projectId: "default",
    sessionId: "example-4",
    activeFile: "src/utils.ts",
  });

  try {
    const result = await tools.write(
      "Create a TypeScript utility function for deep cloning nested objects with cycle detection"
    );

    console.log("Task ID:", result.taskId);
    console.log("Summary:", result.summary);
    console.log("\nGenerated Code Preview:");
    console.log(result.generatedCode);
    console.log("\nPlan Steps:");
    result.plan.forEach((step, index) =>
      console.log(`  ${index + 1}. ${step.description}`)
    );
    console.log("\nRollback actions available:", result.rollbackActions.length);
  } catch (error) {
    console.error("Error:", error);
  }
}

/**
 * Example 5: Quick Workflow - Plan, Write, Execute
 */
export async function example5_quickWorkflow() {
  console.log("Example 5: Quick Workflow (With Changes)\n");

  try {
    const result = await quickWorkflow(
      "Add comprehensive error handling to the API route handler with proper logging and status codes",
      {
        projectId: "default",
        sessionId: "example-5",
        activeFile: "src/routes/api.ts",
      }
    );

    console.log("Task ID:", result.taskId);
    console.log("Summary:", result.summary);
    console.log("Applied Changes:", result.appliedChanges);
    console.log("Verification Status:", result.verificationStatus);
    console.log("\nSuccess Message:");
    console.log(result.successMessage);
  } catch (error) {
    console.error("Error:", error);
  }
}

/**
 * Example 6: Error Fixing
 */
export async function example6_fixErrors() {
  console.log("Example 6: Fix Code Errors\n");

  const tools = createAgenticTools(undefined, {
    projectId: "default",
    sessionId: "example-6",
    activeFile: "src/broken.ts",
  });

  try {
    const result = await tools.fix(
      "Fix all TypeScript compilation errors in this file"
    );

    console.log("Task ID:", result.taskId);
    console.log("Summary:", result.summary);
    console.log("\nFix Preview:");
    console.log(result.generatedCode);
  } catch (error) {
    console.error("Error:", error);
  }
}

/**
 * Example 7: Streaming Chat with Callbacks
 */
export async function example7_streamingPlan() {
  console.log("Example 7: Streaming Plan with Callbacks\n");

  try {
    const plan = await streamPlanning(
      "Analyze the authentication flow and identify potential security vulnerabilities",
      (chunk: string) => {
        process.stdout.write(chunk);
      },
      {
        projectId: "default",
        sessionId: "example-7",
      }
    );

    console.log("\n\nCompleted. Task ID:", plan.taskId);
  } catch (error) {
    console.error("Error:", error);
  }
}

/**
 * Example 8: Full Workflow with Context Management
 */
export async function example8_fullWorkflow() {
  console.log("Example 8: Full Workflow with Context\n");

  const tools = createAgenticTools(undefined, {
    projectId: "default",
    sessionId: "example-8",
  });

  try {
    console.log("Phase 1: Planning...");
    const plan = await tools.plan(
      "Create a new authentication middleware for Express"
    );
    console.log("Plan complete. Task ID:", plan.taskId);
    console.log("  Steps:", plan.plan.steps.length);

    console.log("\nPhase 2: Writing...");
    tools.setContext({
      activeFile: "src/middleware/auth.ts",
    });
    const write = await tools.write(
      "Implement the authentication middleware based on the plan"
    );
    console.log("Code written. Task ID:", write.taskId);

    console.log("\nPhase 3: Executing...");
    const execute = await tools.execute(
      "Apply the authentication middleware changes to the codebase"
    );
    console.log("Changes applied. Task ID:", execute.taskId);
    console.log("  Files affected:", execute.discoveredFiles.length);

    console.log("\nWorkflow complete!");
  } catch (error) {
    console.error("Error:", error);
  }
}

/**
 * Example 9: Health Check and Retry
 */
export async function example9_healthCheck() {
  console.log("Example 9: Health Check with Retry\n");

  const tools = createAgenticTools();

  try {
    console.log("Checking Orexso health...");
    const isHealthy = await tools.healthCheck(3);

    if (isHealthy) {
      console.log("Orexso is healthy and ready");
    } else {
      console.log("Orexso is not responding");
    }
  } catch (error) {
    console.error("Error:", error);
  }
}

/**
 * Example 10: Session Management
 */
export async function example10_sessionManagement() {
  console.log("Example 10: Session Management\n");

  const tools = createAgenticTools();

  try {
    const sessionId = `session-${Date.now()}`;
    tools.createSession(sessionId);
    console.log("Created session:", sessionId);

    const context = tools.getContext();
    console.log("Current context:", context);

    tools.setContext({
      activeFile: "src/component.tsx",
      selection: "handleClick() { ... }",
    });

    console.log("Updated context:", tools.getContext());

    const plan = await tools.plan(
      "Optimize this callback function for performance"
    );
    console.log("Plan created with context. Task ID:", plan.taskId);
  } catch (error) {
    console.error("Error:", error);
  }
}

/**
 * Run a specific example
 */
export async function runExample(exampleNumber: number) {
  const examples: Record<number, () => Promise<void>> = {
    1: example1_simpleChat,
    2: example2_streamingChat,
    3: example3_planning,
    4: example4_writeCode,
    5: example5_quickWorkflow,
    6: example6_fixErrors,
    7: example7_streamingPlan,
    8: example8_fullWorkflow,
    9: example9_healthCheck,
    10: example10_sessionManagement,
  };

  const example = examples[exampleNumber];
  if (!example) {
    console.error(`Example ${exampleNumber} not found`);
    return;
  }

  try {
    await example();
  } catch (error) {
    console.error(`Example ${exampleNumber} failed:`, error);
  }
}

/**
 * Run all examples (with delays between them)
 */
export async function runAllExamples() {
  const delay = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

  for (let index = 1; index <= 10; index++) {
    console.log("\n" + "=".repeat(60));
    await runExample(index);
    if (index < 10) {
      console.log("\nWaiting before next example...");
      await delay(2000);
    }
  }
}

const isMainModule =
  process.argv[1] != null &&
  import.meta.url === new URL(`file://${process.argv[1].replace(/\\/g, "/")}`).href;

if (isMainModule) {
  const exampleNum = parseInt(process.argv[2] || "1", 10);
  runExample(exampleNum).catch(console.error);
}
