import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { loadRegistry } from "./registry.mjs";

export function syncMdiCatalog(rootDir) {
  const registry = loadRegistry(rootDir);
  const applications = registry.applications.map(toMdiApplication).filter(Boolean);
  const file = resolve(registry.root, "packages", "ui", "src", "layouts", "mdi-main", "mdi-app-catalog.generated.ts");
  writeFileSync(file, `${source(applications)}\n`, "utf8");
  return file;
}

function toMdiApplication(application) {
  if (!application.mdi) return undefined;
  return {
    icon: application.mdi.icon,
    id: application.id,
    label: application.label,
    localUrlKey: application.mdi.localUrlKey,
    path: application.mdi.path,
  };
}

function source(applications) {
  return `// Generated by @codexsun/app-cli. Do not edit manually.\n\nexport type MdiCatalogApplication = {\n  icon: string;\n  id: string;\n  label: string;\n  localUrlKey: string;\n  path: string;\n};\n\nexport const mdiCatalogApplications: readonly MdiCatalogApplication[] = ${JSON.stringify(applications, null, 2)} as const;`;
}
