import cors from "@fastify/cors";
import helmet from "@fastify/helmet";
import swagger from "@fastify/swagger";
import swaggerUi from "@fastify/swagger-ui";
import Fastify from "fastify";
import { jsonSchemaTransform, serializerCompiler, validatorCompiler, type ZodTypeProvider } from "fastify-type-provider-zod";
import { resolve } from "node:path";
import { z } from "zod";
import { createPlatformRuntime, loadEnabledAddonProviders, readApplicationDeployableProfile } from "@codexsun/platform-core";
import { readConfig } from "./config.js";
import { InfrasStore } from "./modules/infras/infras-store.js";
import { OrshipInfrasProvider } from "./modules/infras/provider.js";
import { registerInfrasRoutes } from "./modules/infras/routes.js";
import { OrshipFoundationProvider } from "./modules/foundation/provider.js";

const config = readConfig();
const provider = new OrshipFoundationProvider();
const infrasProvider = new OrshipInfrasProvider();
const infrasStore = new InfrasStore(resolve(process.cwd(), "../../../storage/apps/orship/private/data/orship_db.sqlite"));
const profile = readApplicationDeployableProfile({ applicationId: "orship", availableProviderIds: ["platform.core", provider.manifest.id, infrasProvider.manifest.id] });
const runtime = createPlatformRuntime(profile, [provider, infrasProvider, ...(await loadEnabledAddonProviders(profile))]);
runtime.start();
const app = Fastify({ logger: true }).withTypeProvider<ZodTypeProvider>();
app.setValidatorCompiler(validatorCompiler);
app.setSerializerCompiler(serializerCompiler);
await app.register(helmet);
await app.register(cors, { origin: process.env.ORSHIP_WEB_ORIGIN, methods: ["GET", "HEAD", "OPTIONS"], allowedHeaders: ["Authorization", "Content-Type"] });
await app.register(swagger, { openapi: { info: { title: "Orship API", version: "1.0.0" }, openapi: "3.0.3" }, transform: jsonSchemaTransform });
await app.register(swaggerUi, { routePrefix: "/api/internal/reference", uiHooks: { onRequest: (request, reply, done) => { if (request.headers.authorization !== `Bearer ${config.apiReferenceToken}`) return reply.code(401).send({ error: "Authentication required." }); done(); } } });
app.setErrorHandler((error, _request, reply) => { app.log.error(error); return reply.code(500).send({ error: "Internal server error.", code: "server.internal" }); });
app.get("/api/v1/orship/health", { schema: { response: { 200: z.object({ status: z.literal("ok"), providers: z.array(z.string()) }) }, tags: ["System"] } }, async () => ({ status: "ok" as const, providers: [...runtime.enabledProviderIds] }));
await registerInfrasRoutes(app, infrasStore);
app.addHook("onClose", () => runtime.stop());
app.addHook("onClose", () => infrasStore.close());
await app.listen({ host: config.host, port: config.port });
