import { ArrowRightIcon, CheckIcon } from "lucide-react";
import { clientPath, type ClientSite } from "../shared/client-data";
import { Seo, StructuredData } from "../shared/seo";
import { PortfolioSections } from "./portfolio-sections";

type PageKind = "about" | "services" | "work" | "contact";

export function ClientSitePage({ client, page = "overview" }: { client: ClientSite; page?: PageKind | "overview" }) {
  const title = page === "overview" ? client.seo.title : `${page[0].toUpperCase()}${page.slice(1)} | ${client.name}`;
  const description = page === "overview" ? client.seo.description : `${page[0].toUpperCase()}${page.slice(1)} for ${client.name}. ${client.description}`;
  return <><Seo title={title} description={description} keywords={client.seo.keywords} /><StructuredData data={{ "@context": "https://schema.org", "@type": "WebPage", name: title, description, about: { "@type": "Organization", name: client.name } }} /><main className="mx-auto max-w-6xl px-6 pb-24 pt-10 lg:px-10">{page === "overview" ? <Overview client={client} /> : <SubPage client={client} page={page} />}</main></>;
}

function Overview({ client }: { client: ClientSite }) {
  return <><section className="grid gap-12 pb-20 pt-12 lg:grid-cols-[1fr_0.8fr] lg:items-end"><div><p className="mb-7 text-sm uppercase tracking-[0.24em] text-cyan-300">{client.eyebrow}</p><h1 className="max-w-3xl text-5xl font-semibold tracking-[-0.05em] text-white sm:text-7xl">{client.statement}</h1><p className="mt-7 max-w-xl text-lg leading-8 text-slate-400">{client.description}</p><a className="mt-9 inline-flex items-center rounded-full bg-white px-5 py-3 text-sm font-semibold text-slate-950 hover:bg-cyan-200" href={`/clients/${client.slug}/contact`}>{client.contactLabel} <ArrowRightIcon className="ml-2 size-4" /></a></div><IdentityCard client={client} /></section><PortfolioSections client={client} /></>;
}

function SubPage({ client, page }: { client: ClientSite; page: PageKind }) {
  const headings = { about: "A point of view with room to move.", services: "What we make possible.", work: "Selected work and useful outcomes.", contact: "Bring the next good problem." };
  return <><section className="max-w-3xl pb-16 pt-12"><p className="text-sm uppercase tracking-[0.24em] text-cyan-300">{client.name} / {page}</p><h1 className="mt-5 text-5xl font-semibold tracking-[-0.05em] text-white sm:text-6xl">{headings[page]}</h1><p className="mt-6 text-lg leading-8 text-slate-400">{client.description}</p></section>{page === "about" && <AboutContent client={client} />}{page === "services" && <ServiceContent client={client} />}{page === "work" && <WorkPreview client={client} />}{page === "contact" && <ContactContent client={client} />}</>;
}

function IdentityCard({ client }: { client: ClientSite }) { return <div className="rounded-[2rem] border border-cyan-300/25 bg-cyan-300/10 p-8"><div className="flex items-center justify-between"><span className="text-sm text-slate-400">Client identity</span><span className="text-5xl font-semibold text-cyan-300">{client.mark}</span></div><p className="mt-20 max-w-xs text-2xl font-medium leading-tight text-white">{client.featured}</p><div className="mt-8 grid grid-cols-3 gap-3">{client.stats.map((stat) => <div key={stat.label} className="border-t border-white/15 pt-3"><p className="text-xs uppercase tracking-widest text-slate-500">{stat.label}</p><p className="mt-2 text-sm font-medium text-slate-200">{stat.value}</p></div>)}</div></div>; }
function AboutContent({ client }: { client: ClientSite }) { return <section className="grid gap-10 border-t border-white/10 py-14 md:grid-cols-[0.8fr_1.2fr]"><h2 className="text-2xl font-semibold text-white">Our approach</h2><div className="grid gap-3">{client.approach.map((step, index) => <div key={step} className="flex items-center gap-4 border-b border-white/10 py-5 text-lg text-slate-200"><span className="text-sm text-cyan-300">0{index + 1}</span>{step}</div>)}</div></section>; }
function ServiceContent({ client }: { client: ClientSite }) { return <section className="grid gap-3 border-t border-white/10 py-14 md:grid-cols-3">{client.services.map((service) => <div key={service} className="min-h-44 rounded-2xl border border-white/10 bg-white/[0.03] p-6"><CheckIcon className="size-5 text-cyan-300" /><h2 className="mt-10 text-lg font-semibold text-white">{service}</h2><p className="mt-3 text-sm leading-6 text-slate-400">A considered, modular capability shaped around the needs of {client.name}.</p></div>)}</section>; }
function WorkPreview({ client }: { client: ClientSite }) { return <section className="border-t border-white/10 py-14"><div className="mb-8 flex items-end justify-between gap-6"><div><p className="text-sm uppercase tracking-[0.24em] text-slate-500">Selected work</p><h2 className="mt-3 text-3xl font-semibold tracking-tight text-white">Useful work, clearly presented.</h2></div><a className="hidden text-sm text-cyan-300 hover:text-white sm:block" href={clientPath(client.slug, "contact")}>Discuss a project <ArrowRightIcon className="ml-1 inline size-4" /></a></div><div className="grid gap-4 md:grid-cols-3">{client.work.map((item) => <article key={item.title} className="min-h-64 border-t border-white/15 pt-5"><p className="text-sm text-cyan-300">{item.type}</p><h3 className="mt-12 text-xl font-semibold text-white">{item.title}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{item.description}</p></article>)}</div></section>; }
function ContactContent({ client }: { client: ClientSite }) { const email = client.contact?.email || (import.meta.env.VITE_SITES_CONTACT_EMAIL as string | undefined); return <section className="grid gap-4 border-t border-white/10 py-14 md:grid-cols-2"><div className="rounded-[2rem] border border-cyan-300/25 bg-cyan-300/10 p-8"><p className="text-sm uppercase tracking-[0.24em] text-cyan-200">{client.contact?.label ?? client.contactLabel}</p><p className="mt-5 text-lg leading-8 text-slate-200">Tell us what you are trying to make, improve, or understand.</p>{email ? <a className="mt-8 inline-flex items-center rounded-full bg-white px-5 py-3 text-sm font-semibold text-slate-950 hover:bg-cyan-200" href={`mailto:${email}`}>Email the team <ArrowRightIcon className="ml-2 size-4" /></a> : <p className="mt-8 text-sm text-cyan-200">Contact details will be added by the editor.</p>}</div><div className="rounded-[2rem] border border-white/10 bg-white/[0.03] p-8"><p className="text-sm uppercase tracking-[0.24em] text-slate-500">Visit or connect</p>{client.location ? <p className="mt-5 text-lg leading-8 text-slate-200">{client.location.address}</p> : null}{client.contact?.phone ? <p className="mt-4 text-sm text-slate-400">{client.contact.phone}</p> : null}<div className="mt-8 flex flex-wrap gap-3">{(client.socialLinks ?? []).map((link) => <a key={link.href} className="rounded-full border border-white/15 px-4 py-2 text-sm text-slate-300 hover:border-white/40 hover:text-white" href={link.href} rel="noreferrer" target="_blank">{link.label}</a>)}</div></div></section>; }
