import { ArrowRightIcon, BriefcaseBusinessIcon, Layers3Icon } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@codexsun/ui/components/card";
import { WorkspaceActionCard, WorkspacePageHeader } from "@codexsun/ui/blocks/workspace";
import { clientPath, getClientSections, type ClientSite, type SiteSection } from "../shared/client-data";

export function PortfolioSections({ client }: { client: ClientSite }) {
  return <div className="grid gap-16">{getClientSections(client).map((section) => <PortfolioSectionTemplate key={section.type} client={client} section={section} />)}</div>;
}

function PortfolioSectionTemplate({ client, section }: { client: ClientSite; section: SiteSection }) {
  if (section.type === "about") return <section className="grid gap-8 border-t border-white/10 pt-14 md:grid-cols-[0.8fr_1.2fr]"><WorkspacePageHeader className="text-white" eyebrow="About" title={section.title} description="A reusable editorial section stored as client content." /><p className="max-w-2xl text-lg leading-8 text-slate-400">{section.body}</p></section>;
  if (section.type === "services") return <section className="grid gap-8 border-t border-white/10 pt-14"><WorkspacePageHeader className="text-white" eyebrow="Capabilities" title={section.title} /><div className="grid gap-4 md:grid-cols-3">{section.items.map((item) => <WorkspaceActionCard key={item} className="border-white/10 bg-white/[0.04] text-white" icon={BriefcaseBusinessIcon} title={item} description={`A modular capability shaped around ${client.name}.`} layout="stacked" />)}</div></section>;
  if (section.type === "work") return <section className="grid gap-8 border-t border-white/10 pt-14"><WorkspacePageHeader className="text-white" eyebrow="Portfolio" title={section.title} /><div className="grid gap-4 md:grid-cols-3">{section.items.map((item) => <Card key={item.title} className="min-h-64 border-white/10 bg-white/[0.04] text-white"><CardHeader><span className="text-sm text-cyan-300">{item.type}</span><CardTitle className="mt-10 text-xl">{item.title}</CardTitle></CardHeader><CardContent className="text-sm leading-6 text-slate-400">{item.description}</CardContent></Card>)}</div></section>;
  if (section.type === "approach") return <section className="grid gap-8 border-t border-white/10 pt-14 md:grid-cols-[0.8fr_1.2fr]"><WorkspacePageHeader className="text-white" eyebrow="Process" title={section.title} /><div className="grid gap-3">{section.items.map((item, index) => <div key={item} className="flex items-center gap-4 border-b border-white/10 py-5 text-lg text-slate-200"><span className="text-sm text-cyan-300">0{index + 1}</span><Layers3Icon className="size-4 text-slate-500" />{item}</div>)}</div></section>;
  return <section className="border-t border-white/10 pt-14"><Card className="border-cyan-300/25 bg-cyan-300/10 text-white"><CardContent className="flex flex-col gap-6 p-8 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-lg leading-8 text-slate-200">{section.label}</p><p className="mt-2 text-sm text-slate-400">A reusable call-to-action section controlled by the editor.</p></div><a className="inline-flex shrink-0 items-center rounded-full bg-white px-5 py-3 text-sm font-semibold text-slate-950 hover:bg-cyan-200" href={clientPath(client.slug, "contact")}>Start a conversation <ArrowRightIcon className="ml-2 size-4" /></a></CardContent></Card></section>;
}
