# This file is reserved for approved prerequisite image customizations.
# The default stack uses upstream images directly.
ARG BASE_IMAGE=filebrowser/filebrowser
ARG BASE_TAG=v2.32.0
FROM ${BASE_IMAGE}:${BASE_TAG}
