import type {
  ZetroGuardrailTemplate,
  ZetroPlaybook,
  ZetroSampleFinding,
  ZetroSampleRun,
} from "./playbook-contracts.js"

export const zetroStaticPlaybooks: ZetroPlaybook[] = [
  {
    id: "feature-dev",
    name: "Feature Development",
    kind: "workflow",
    family: "feature-dev",
    summary: "Seven-phase implementation workflow for complex feature work.",
    description: "Moves from discovery through repo exploration, architecture, implementation, review, and final summary.",
    defaultOutputMode: "maximum",
    riskLevel: "medium",
    requiresApproval: false,
    status: "active",
    reviewLanes: ["architecture", "bug", "test", "simplification"],
    phases: [
      {
        id: "discovery",
        name: "Discovery",
        objective: "Clarify the request, product goal, constraints, and done criteria.",
        expectedOutput: "Intent, assumptions, unresolved questions, and success criteria.",
        approvalGate: false,
      },
      {
        id: "exploration",
        name: "Codebase Exploration",
        objective: "Find existing patterns, owners, routes, APIs, and data flows.",
        expectedOutput: "Repo context, file map, and relevant precedents.",
        approvalGate: false,
      },
      {
        id: "architecture",
        name: "Architecture Design",
        objective: "Choose the app-owned design that fits current boundaries.",
        expectedOutput: "Architecture decision, tradeoffs, and implementation phases.",
        approvalGate: true,
      },
      {
        id: "implementation",
        name: "Implementation",
        objective: "Apply scoped changes and keep the worktree understandable.",
        expectedOutput: "Changed files, behavior notes, and local verification.",
        approvalGate: true,
      },
      {
        id: "review",
        name: "Quality Review",
        objective: "Check bugs, tests, type design, conventions, and simplification.",
        expectedOutput: "Structured findings and fix recommendations.",
        approvalGate: false,
      },
    ],
  },
  {
    id: "code-review",
    name: "Code Review",
    kind: "review",
    family: "code-review",
    summary: "Focused review workflow for bugs, regressions, and repo-rule violations.",
    description: "Produces finding-first review output with severity, confidence, and file references.",
    defaultOutputMode: "audit",
    riskLevel: "low",
    requiresApproval: false,
    status: "active",
    reviewLanes: ["bug", "security", "convention", "test"],
    phases: [
      {
        id: "scope",
        name: "Scope",
        objective: "Identify changed files and intended behavior.",
        expectedOutput: "Review scope and relevant context.",
        approvalGate: false,
      },
      {
        id: "findings",
        name: "Findings",
        objective: "Prioritize correctness, security, regressions, and missing tests.",
        expectedOutput: "Ordered findings with file references.",
        approvalGate: false,
      },
    ],
  },
  {
    id: "pr-review-toolkit",
    name: "Review Toolkit",
    kind: "review",
    family: "pr-review-toolkit",
    summary: "Multi-lane review for comments, tests, errors, types, code, and simplification.",
    description: "Splits a review into independent lanes and consolidates high-confidence findings.",
    defaultOutputMode: "audit",
    riskLevel: "medium",
    requiresApproval: false,
    status: "active",
    reviewLanes: ["comment", "test", "error", "type-design", "simplification"],
    phases: [
      {
        id: "lane-selection",
        name: "Lane Selection",
        objective: "Choose which review lanes apply to the work.",
        expectedOutput: "Selected review lanes and priority.",
        approvalGate: false,
      },
      {
        id: "consolidation",
        name: "Consolidation",
        objective: "Merge lane findings into one finding-first review.",
        expectedOutput: "Deduplicated findings with severity and confidence.",
        approvalGate: false,
      },
    ],
  },
  {
    id: "security-guidance",
    name: "Security Guidance",
    kind: "guardrail",
    family: "security-guidance",
    summary: "Advisory guardrails for risky files, commands, and unsafe code patterns.",
    description: "Starts as visible guidance before any blocking behavior is enabled.",
    defaultOutputMode: "normal",
    riskLevel: "high",
    requiresApproval: true,
    status: "active",
    reviewLanes: ["security", "convention"],
    phases: [
      {
        id: "scan",
        name: "Scan",
        objective: "Identify risky operation categories before execution.",
        expectedOutput: "Warnings, approvals needed, and safe alternatives.",
        approvalGate: false,
      },
    ],
  },
  {
    id: "plugin-dev",
    name: "Playbook Development",
    kind: "workflow",
    family: "plugin-dev",
    summary: "Create new Zetro playbooks using a guided design and validation workflow.",
    description: "Adapts plugin creation ideas into Codexsun-owned playbook authoring.",
    defaultOutputMode: "maximum",
    riskLevel: "medium",
    requiresApproval: false,
    status: "draft",
    reviewLanes: ["architecture", "test", "convention"],
    phases: [
      {
        id: "define",
        name: "Define",
        objective: "Define playbook purpose, inputs, phases, output mode, and risk.",
        expectedOutput: "Typed playbook draft.",
        approvalGate: false,
      },
      {
        id: "validate",
        name: "Validate",
        objective: "Review playbook boundaries and approval gates.",
        expectedOutput: "Validation notes and activation readiness.",
        approvalGate: true,
      },
    ],
  },
  {
    id: "commit-commands",
    name: "Approved Git Workflow",
    kind: "command",
    family: "commit-commands",
    summary: "Future approval-gated git helper flow for commit, push, and PR actions.",
    description: "Deferred until Zetro has persistent approvals and command output capture.",
    defaultOutputMode: "audit",
    riskLevel: "critical",
    requiresApproval: true,
    status: "paused",
    reviewLanes: ["security", "convention"],
    phases: [
      {
        id: "proposal",
        name: "Proposal",
        objective: "Show planned git commands and affected files.",
        expectedOutput: "Approval request with command list.",
        approvalGate: true,
      },
    ],
  },
]

export const zetroGuardrailTemplates: ZetroGuardrailTemplate[] = [
  {
    id: "repo-instructions",
    name: "Repo Instructions",
    event: "before-plan",
    severity: "info",
    summary: "Read app boundaries and design-system defaults before UI work.",
  },
  {
    id: "destructive-command",
    name: "Destructive Command Approval",
    event: "before-command",
    severity: "blocking",
    summary: "Require explicit approval for destructive shell or git commands.",
  },
  {
    id: "sensitive-write",
    name: "Sensitive Write Warning",
    event: "before-write",
    severity: "warning",
    summary: "Warn before editing auth, environment, migration, or runner code.",
  },
  {
    id: "review-before-complete",
    name: "Review Before Complete",
    event: "before-complete",
    severity: "info",
    summary: "Run a focused review and record findings before marking a run complete.",
  },
]

export const zetroSampleRuns: ZetroSampleRun[] = [
  {
    id: "run-static-catalog",
    title: "Build static maximum-output catalog",
    playbookId: "feature-dev",
    status: "running",
    outputMode: "maximum",
    summary: "Phase 1 app surface with static playbooks, guardrails, findings, and settings.",
  },
  {
    id: "run-review-plan",
    title: "Review Zetro build plan",
    playbookId: "code-review",
    status: "awaiting-approval",
    outputMode: "audit",
    summary: "Finding-first review of the initial Zetro app scaffold and navigation wiring.",
  },
]

export const zetroSampleFindings: ZetroSampleFinding[] = [
  {
    id: "finding-runner-policy",
    runId: "run-review-plan",
    title: "Runner policy must exist before command execution",
    category: "security",
    severity: "high",
    confidence: 95,
    status: "open",
    summary: "Approved CLI runner should stay deferred until allowlists, approvals, and output capture exist.",
  },
  {
    id: "finding-persistence",
    runId: "run-static-catalog",
    title: "Run console needs persistence before automation",
    category: "architecture",
    severity: "medium",
    confidence: 90,
    status: "accepted",
    summary: "Manual runs should persist first so every later runner mode has the same audit path.",
  },
]
