import type { InterfaceTopologySection } from '@codexsun/ui/features/interface-topology'

export const docsTopologySections: readonly InterfaceTopologySection[] = [
  {
    id: '10',
    technicalName: 'docs.library.workspace',
    name: 'Docs library workspace',
    scope: 'Docs',
    description: 'Hosts document navigation, loading state, reading canvas, and connections.',
  },
  {
    id: '10.1',
    technicalName: 'docs.library.summaryBanner',
    name: 'Library summary banner',
    scope: 'Docs library',
    description: 'Shows the library name and visible document count.',
  },
  {
    id: '10.2',
    technicalName: 'docs.library.readerCanvas',
    name: 'Reader canvas',
    scope: 'Docs library',
    description: 'Shows the selected document, overview, loading state, or error state.',
  },
  {
    id: '10.2.1',
    technicalName: 'docs.reader.documentBody',
    name: 'Document body',
    scope: 'Reader canvas',
    description: 'Renders the selected Markdown or MDX document.',
  },
  {
    id: '10.2.2',
    technicalName: 'docs.reader.pageOutline',
    name: 'Page outline',
    scope: 'Reader canvas',
    description: 'Navigates headings in the selected document.',
  },
  {
    id: '10.2.3',
    technicalName: 'docs.reader.connections',
    name: 'Document connections',
    scope: 'Reader canvas',
    description: 'Shows linked notes, backlinks, and tag-related documents.',
  },
  {
    id: '10.2.4',
    technicalName: 'docs.reader.documentNavigation',
    name: 'Document navigation',
    scope: 'Reader canvas',
    description: 'Opens the previous or next document in the repository index order.',
  },
  {
    id: '10.3',
    technicalName: 'docs.overview.banner',
    name: 'Docs overview banner',
    scope: 'Docs overview',
    description: 'Introduces the connected documentation library.',
  },
  {
    id: '10.3.1',
    technicalName: 'docs.overview.metrics',
    name: 'Overview metrics',
    scope: 'Docs overview',
    description: 'Summarizes document count, source model, and connections.',
  },
  {
    id: '10.3.2',
    technicalName: 'docs.overview.openArchitecture',
    name: 'Open architecture',
    scope: 'Docs overview',
    description: 'Opens the architecture document.',
  },
  {
    id: '10.4',
    technicalName: 'docs.error.unavailableBanner',
    name: 'Docs unavailable banner',
    scope: 'Docs library',
    description: 'Explains how to recover when the Docs API is unavailable.',
  },
  {
    id: '11',
    technicalName: 'docs.ideas.workspace',
    name: 'Ideas workspace',
    scope: 'Docs',
    description: 'Explains the current framework development direction.',
  },
  {
    id: '11.1',
    technicalName: 'docs.ideas.summaryBanner',
    name: 'Ideas summary banner',
    scope: 'Ideas workspace',
    description: 'Introduces the development plan.',
  },
  {
    id: '11.2',
    technicalName: 'docs.ideas.developmentFlow',
    name: 'Development flow',
    scope: 'Ideas workspace',
    description: 'Shows the delivery path from consumer need to verified release.',
  },
  {
    id: '11.3',
    technicalName: 'docs.ideas.ownershipPattern',
    name: 'Ownership pattern',
    scope: 'Ideas workspace',
    description: 'Separates Framework, Platform Core, and application ownership.',
  },
  {
    id: '11.4',
    technicalName: 'docs.ideas.deliveryPlan',
    name: 'Delivery plan',
    scope: 'Ideas workspace',
    description: 'Shows the five-stage implementation order.',
  },
  {
    id: '11.5',
    technicalName: 'docs.ideas.guardrails',
    name: 'Guardrails',
    scope: 'Ideas workspace',
    description: 'Lists boundaries that keep shared code focused.',
  },
  {
    id: '11.6',
    technicalName: 'docs.ideas.architectureSummary',
    name: 'Architecture standards summary',
    scope: 'Ideas workspace',
    description: 'Introduces global standards for a multi-developer repository.',
  },
  {
    id: '11.7',
    technicalName: 'docs.ideas.architectureChangePath',
    name: 'Architecture change path',
    scope: 'Ideas workspace',
    description: 'Shows the path from a product need to verified change.',
  },
  {
    id: '11.8',
    technicalName: 'docs.ideas.architectureStandards',
    name: 'Team standards',
    scope: 'Ideas workspace',
    description: 'Lists the global ownership, contract, dependency, and proof standards.',
  },
  {
    id: '11.9',
    technicalName: 'docs.ideas.architectureComparison',
    name: 'Repository standards comparison',
    scope: 'Ideas workspace',
    description: 'Compares global architecture standards with current CODEXSUN patterns.',
  },
  {
    id: '11.10',
    technicalName: 'docs.ideas.architectureAgreement',
    name: 'Working agreement',
    scope: 'Ideas workspace',
    description: 'Summarizes the expected contributor workflow.',
  },
  {
    id: '11.11',
    technicalName: 'docs.ideas.monorepoSummary',
    name: 'Multi-app monorepo summary',
    scope: 'Ideas workspace',
    description: 'Introduces the multiple-application repository model.',
  },
  {
    id: '11.12',
    technicalName: 'docs.ideas.monorepoMap',
    name: 'Shared package and application map',
    scope: 'Ideas workspace',
    description: 'Shows named shared packages, source-owned applications, and the runtime holder.',
  },
  {
    id: '11.13',
    technicalName: 'docs.ideas.sharedUi',
    name: 'Shared UI package',
    scope: 'Ideas workspace',
    description: 'Explains the package-owned visual capabilities shared by browser applications.',
  },
  {
    id: '11.14',
    technicalName: 'docs.ideas.uiOwnership',
    name: 'UI ownership boundary',
    scope: 'Ideas workspace',
    description: 'Separates reusable UI behavior from application-owned product behavior.',
  },
  {
    id: '11.15',
    technicalName: 'docs.ideas.monorepoPractices',
    name: 'Monorepo practices',
    scope: 'Ideas workspace',
    description: 'Lists the working practices that keep the repository maintainable.',
  },
  {
    id: '11.16',
    technicalName: 'docs.ideas.monorepoComparison',
    name: 'Repository model comparison',
    scope: 'Ideas workspace',
    description: 'Compares a single application with the CODEXSUN multi-app model.',
  },
  {
    id: '11.17',
    technicalName: 'docs.ideas.monorepoChecklist',
    name: 'Cross-application checklist',
    scope: 'Ideas workspace',
    description: 'Lists the checks required before a cross-application change.',
  },
]
