import type { InterfaceTopologySection } from '@codexsun/ui/features/interface-topology'

export const docsTopologySections: readonly InterfaceTopologySection[] = [
  {
    id: '10',
    technicalName: 'docs.library.workspace',
    name: 'Docs library workspace',
    scope: 'Docs',
    description: 'Hosts document navigation, loading state, reading canvas, and connections.',
  },
  {
    id: '10.1',
    technicalName: 'docs.library.summaryBanner',
    name: 'Library summary banner',
    scope: 'Docs library',
    description: 'Shows the library name and visible document count.',
  },
  {
    id: '10.2',
    technicalName: 'docs.library.readerCanvas',
    name: 'Reader canvas',
    scope: 'Docs library',
    description: 'Shows the selected document, overview, loading state, or error state.',
  },
  {
    id: '10.2.1',
    technicalName: 'docs.reader.documentBody',
    name: 'Document body',
    scope: 'Reader canvas',
    description: 'Renders the selected Markdown or MDX document.',
  },
  {
    id: '10.2.2',
    technicalName: 'docs.reader.pageOutline',
    name: 'Page outline',
    scope: 'Reader canvas',
    description: 'Navigates headings in the selected document.',
  },
  {
    id: '10.2.3',
    technicalName: 'docs.reader.connections',
    name: 'Document connections',
    scope: 'Reader canvas',
    description: 'Shows linked notes, backlinks, and tag-related documents.',
  },
  {
    id: '10.2.4',
    technicalName: 'docs.reader.documentNavigation',
    name: 'Document navigation',
    scope: 'Reader canvas',
    description: 'Opens the previous or next document in the repository index order.',
  },
  {
    id: '10.3',
    technicalName: 'docs.overview.banner',
    name: 'Docs overview banner',
    scope: 'Docs overview',
    description: 'Introduces the connected documentation library.',
  },
  {
    id: '10.3.1',
    technicalName: 'docs.overview.metrics',
    name: 'Overview metrics',
    scope: 'Docs overview',
    description: 'Summarizes document count, source model, and connections.',
  },
  {
    id: '10.3.2',
    technicalName: 'docs.overview.openArchitecture',
    name: 'Open architecture',
    scope: 'Docs overview',
    description: 'Opens the architecture document.',
  },
  {
    id: '10.4',
    technicalName: 'docs.error.unavailableBanner',
    name: 'Docs unavailable banner',
    scope: 'Docs library',
    description: 'Explains how to recover when the Docs API is unavailable.',
  },
  {
    id: '11',
    technicalName: 'docs.ideas.workspace',
    name: 'Ideas workspace',
    scope: 'Docs',
    description: 'Explains the current framework development direction.',
  },
  {
    id: '11.1',
    technicalName: 'docs.ideas.summaryBanner',
    name: 'Ideas summary banner',
    scope: 'Ideas workspace',
    description: 'Introduces the development plan.',
  },
  {
    id: '11.2',
    technicalName: 'docs.ideas.developmentFlow',
    name: 'Development flow',
    scope: 'Ideas workspace',
    description: 'Shows the delivery path from consumer need to verified release.',
  },
  {
    id: '11.3',
    technicalName: 'docs.ideas.ownershipPattern',
    name: 'Ownership pattern',
    scope: 'Ideas workspace',
    description: 'Separates Framework, Platform Core, and application ownership.',
  },
  {
    id: '11.4',
    technicalName: 'docs.ideas.deliveryPlan',
    name: 'Delivery plan',
    scope: 'Ideas workspace',
    description: 'Shows the five-stage implementation order.',
  },
  {
    id: '11.5',
    technicalName: 'docs.ideas.guardrails',
    name: 'Guardrails',
    scope: 'Ideas workspace',
    description: 'Lists boundaries that keep shared code focused.',
  },
]
