import type { IndustryManifest } from "../../apps/framework/manifests/industry-manifest.js"

export const garmentEcommerceIndustryManifest: IndustryManifest = {
  id: "garment-ecommerce",
  kind: "industry",
  displayName: "Garment Ecommerce",
  summary:
    "Garment direct-to-consumer bundle covering storefront, checkout, stock-aware fulfilment, billing, and shared masters.",
  dependencies: [
    { id: "billing", kind: "app" },
    { id: "stock", kind: "app" },
    { id: "ecommerce", kind: "app" },
    { id: "core", kind: "app" },
    { id: "crm", kind: "app", optional: true },
  ],
  enabledApps: ["core", "billing", "stock", "ecommerce", "crm"],
  enabledModuleIds: [
    "core.overview",
    "core.master",
    "core.common",
    "billing.overview",
    "billing.system",
    "billing.books",
    "billing.vouchers",
    "billing.accounts",
    "billing.inventory",
    "billing.reports",
    "stock.overview",
    "stock.inward",
    "stock.outward",
    "stock.operations",
    "ecommerce.overview",
    "ecommerce.storefront",
    "ecommerce.commerce",
    "ecommerce.operations",
    "ecommerce.stock",
    "ecommerce.settings",
    "ecommerce.common",
    "crm.overview",
    "crm.sales",
  ],
  featureFlags: [],
}
