import type { InventoryMovementDirection, InventoryMovementType } from "./stock-movement.js"

export type InventoryMovementEventDefinition = {
  type: InventoryMovementType
  direction: InventoryMovementDirection
  affectsOnHand: boolean
  affectsReserved: boolean
  affectsAllocated: boolean
  requiresLocation: boolean
  requiresReference: boolean
  summary: string
}

export const inventoryMovementEventDefinitions: InventoryMovementEventDefinition[] = [
  {
    type: "purchase-inward",
    direction: "in",
    affectsOnHand: true,
    affectsReserved: false,
    affectsAllocated: false,
    requiresLocation: true,
    requiresReference: true,
    summary: "Increases on-hand stock from supplier inward or receiving.",
  },
  {
    type: "sales-issue",
    direction: "out",
    affectsOnHand: true,
    affectsReserved: false,
    affectsAllocated: true,
    requiresLocation: true,
    requiresReference: true,
    summary: "Reduces issued stock from a sale or fulfilment issue event.",
  },
  {
    type: "sales-return",
    direction: "in",
    affectsOnHand: true,
    affectsReserved: false,
    affectsAllocated: false,
    requiresLocation: true,
    requiresReference: true,
    summary: "Adds stock back from a customer return or reverse issue.",
  },
  {
    type: "purchase-return",
    direction: "out",
    affectsOnHand: true,
    affectsReserved: false,
    affectsAllocated: false,
    requiresLocation: true,
    requiresReference: true,
    summary: "Removes stock sent back to a supplier.",
  },
  {
    type: "transfer-out",
    direction: "out",
    affectsOnHand: true,
    affectsReserved: false,
    affectsAllocated: false,
    requiresLocation: true,
    requiresReference: true,
    summary: "Moves stock out of a source warehouse or location for transfer.",
  },
  {
    type: "transfer-in",
    direction: "in",
    affectsOnHand: true,
    affectsReserved: false,
    affectsAllocated: false,
    requiresLocation: true,
    requiresReference: true,
    summary: "Moves stock into a destination warehouse or location from transfer.",
  },
  {
    type: "adjustment-increase",
    direction: "in",
    affectsOnHand: true,
    affectsReserved: false,
    affectsAllocated: false,
    requiresLocation: true,
    requiresReference: false,
    summary: "Increases stock from audited adjustment or reconciliation.",
  },
  {
    type: "adjustment-decrease",
    direction: "out",
    affectsOnHand: true,
    affectsReserved: false,
    affectsAllocated: false,
    requiresLocation: true,
    requiresReference: false,
    summary: "Decreases stock from audited adjustment or reconciliation.",
  },
  {
    type: "reservation-hold",
    direction: "none",
    affectsOnHand: false,
    affectsReserved: true,
    affectsAllocated: false,
    requiresLocation: false,
    requiresReference: true,
    summary: "Creates a reservation hold without changing physical on-hand stock.",
  },
  {
    type: "reservation-release",
    direction: "none",
    affectsOnHand: false,
    affectsReserved: true,
    affectsAllocated: false,
    requiresLocation: false,
    requiresReference: true,
    summary: "Releases a reservation hold without changing physical on-hand stock.",
  },
  {
    type: "allocation",
    direction: "none",
    affectsOnHand: false,
    affectsReserved: false,
    affectsAllocated: true,
    requiresLocation: true,
    requiresReference: true,
    summary: "Allocates already reserved or available stock to an exact picking or issue flow.",
  },
  {
    type: "deallocation",
    direction: "none",
    affectsOnHand: false,
    affectsReserved: false,
    affectsAllocated: true,
    requiresLocation: true,
    requiresReference: true,
    summary: "Releases previously allocated stock back to the available or reserved pool.",
  },
  {
    type: "damage",
    direction: "out",
    affectsOnHand: true,
    affectsReserved: false,
    affectsAllocated: false,
    requiresLocation: true,
    requiresReference: false,
    summary: "Removes damaged stock from saleable inventory.",
  },
  {
    type: "rejection",
    direction: "out",
    affectsOnHand: true,
    affectsReserved: false,
    affectsAllocated: false,
    requiresLocation: true,
    requiresReference: false,
    summary: "Removes rejected inward stock from the saleable pool.",
  },
  {
    type: "write-off",
    direction: "out",
    affectsOnHand: true,
    affectsReserved: false,
    affectsAllocated: false,
    requiresLocation: true,
    requiresReference: false,
    summary: "Writes off stock as a final controlled inventory loss event.",
  },
]
