export const zetroTableNames = {
  playbooks: "zetro_playbooks",
  playbookPhases: "zetro_playbook_phases",
  runs: "zetro_runs",
  runEvents: "zetro_run_events",
  runOutputSections: "zetro_run_output_sections",
  commandProposals: "zetro_command_proposals",
  commandAllowlist: "zetro_command_allowlist",
  executedCommands: "zetro_executed_commands",
  chatSessions: "zetro_chat_sessions",
  chatMessages: "zetro_chat_messages",
  findings: "zetro_findings",
  guardrails: "zetro_guardrails",
  settings: "zetro_settings",
  loopStates: "zetro_loop_states",
} as const;
