import type { SeedMap } from "./helpers.js"
import { defineItem, defineNamedModuleItem } from "./helpers.js"

export const catalogSeed: SeedMap = {
  productGroups: [
    defineNamedModuleItem("product-group", "apparel", "apparel", "Apparel", "Core apparel assortment."),
    defineNamedModuleItem("product-group", "fabric", "fabric", "Fabric", "Dyed, knitted, and woven fabric lines."),
    defineNamedModuleItem("product-group", "accessories", "accessories", "Accessories", "Complementary accessories and add-ons."),
  ],
  productCategories: [
    defineItem("product-category:ethnic", { code: "ethnic", name: "Ethnic Wear", description: "Festive and premium ethnic silhouettes.", image: "https://placehold.co/320x220/f4ebe1/3b2a20?text=Ethnic", position_order: 10, show_on_storefront_top_menu: true, show_on_storefront_catalog: true }),
    defineItem("product-category:t-shirts", { code: "t-shirts", name: "T-Shirts", description: "Knitted T-shirts and jersey tops.", image: "https://placehold.co/320x220/efe6dc/3b2a20?text=T-Shirts", position_order: 20, show_on_storefront_top_menu: true, show_on_storefront_catalog: true }),
    defineItem("product-category:knitted-fabrics", { code: "knitted-fabrics", name: "Knitted Fabrics", description: "Knitted and dyed cotton fabric range.", image: "https://placehold.co/320x220/f5ece3/3b2a20?text=Knits", position_order: 30, show_on_storefront_top_menu: true, show_on_storefront_catalog: true }),
    defineItem("product-category:accessories", { code: "accessories", name: "Accessories", description: "Utility and styling accessories.", image: "https://placehold.co/320x220/f5ece3/3b2a20?text=Accessories", position_order: 40, show_on_storefront_top_menu: true, show_on_storefront_catalog: true }),
  ],
  productTypes: [
    defineNamedModuleItem("product-type", "finished-good", "finished-good", "Finished Good", "Stocked sellable product."),
    defineNamedModuleItem("product-type", "raw-material", "raw-material", "Raw Material", "Input material for manufacturing."),
    defineNamedModuleItem("product-type", "service", "service", "Service", "Non-stock service item."),
  ],
  units: [
    defineItem("unit:piece", { code: "PCS", name: "Piece", symbol: "pc", description: "Single piece unit." }),
    defineItem("unit:pair", { code: "PAIR", name: "Pair", symbol: "pair", description: "Pair unit for sets." }),
    defineItem("unit:meter", { code: "MTR", name: "Meter", symbol: "m", description: "Fabric meter unit." }),
    defineItem("unit:kilogram", { code: "KG", name: "Kilogram", symbol: "kg", description: "Weight-based inventory unit." }),
  ],
  hsnCodes: [
    defineItem("hsn:6109", { code: "6109", name: "T-Shirts, singlets and other vests, knitted or crocheted", description: "Knitted T-shirts and cotton jersey tops." }),
    defineItem("hsn:6110", { code: "6110", name: "Jerseys, pullovers, cardigans and similar articles, knitted or crocheted", description: "Knitted garments including pullovers and sweatshirts." }),
    defineItem("hsn:6006", { code: "6006", name: "Other knitted or crocheted fabrics", description: "General knitted fabrics including dyed cotton knit fabric." }),
    defineItem("hsn:5209", { code: "5209", name: "Woven cotton fabrics weighing more than 200 g/m2", description: "Heavy cotton dyed and processed woven fabric." }),
    defineItem("hsn:5211", { code: "5211", name: "Woven cotton fabrics mixed with man-made fibres weighing more than 200 g/m2", description: "Dyed cotton-rich woven fabrics used in garment manufacturing." }),
    defineItem("hsn:6205", { code: "6205", name: "Men shirts", description: "Woven shirts and related menswear." }),
  ],
  taxes: [
    defineItem("tax:gst-0", { code: "GST0", name: "GST 0%", tax_type: "gst", rate_percent: 0, description: "Nil GST slab." }),
    defineItem("tax:gst-0-25", { code: "GST0.25", name: "GST 0.25%", tax_type: "gst", rate_percent: 0.25, description: "Quarter percent GST slab." }),
    defineItem("tax:gst-3", { code: "GST3", name: "GST 3%", tax_type: "gst", rate_percent: 3, description: "Three percent GST slab." }),
    defineItem("tax:gst-5", { code: "GST5", name: "GST 5%", tax_type: "gst", rate_percent: 5, description: "Five percent GST slab." }),
    defineItem("tax:gst-12", { code: "GST12", name: "GST 12%", tax_type: "gst", rate_percent: 12, description: "Twelve percent GST slab." }),
    defineItem("tax:gst-18", { code: "GST18", name: "GST 18%", tax_type: "gst", rate_percent: 18, description: "Eighteen percent GST slab." }),
    defineItem("tax:gst-28", { code: "GST28", name: "GST 28%", tax_type: "gst", rate_percent: 28, description: "Twenty-eight percent GST slab." }),
  ],
  brands: [
    defineNamedModuleItem("brand", "aster-loom", "aster-loom", "Aster Loom", "Artisanal festive silhouettes."),
    defineNamedModuleItem("brand", "northline", "northline", "Northline", "Relaxed modern menswear."),
    defineNamedModuleItem("brand", "little-bloom", "little-bloom", "Little Bloom", "Playful premium kidswear."),
  ],
  colours: [
    defineItem("colour:ivory", { code: "ivory", name: "Ivory", hex_code: "#efe6d7", description: "Warm off-white neutral." }),
    defineItem("colour:indigo", { code: "indigo", name: "Indigo", hex_code: "#29446a", description: "Deep indigo blue." }),
    defineItem("colour:sand", { code: "sand", name: "Sand", hex_code: "#c8a67e", description: "Muted sand beige." }),
    defineItem("colour:black", { code: "black", name: "Black", hex_code: "#111111", description: "Core dark neutral." }),
    defineItem("colour:white", { code: "white", name: "White", hex_code: "#ffffff", description: "Core light neutral." }),
  ],
  sizes: [
    defineItem("size:all", { code: "ALL", name: "All Sizes", sort_order: 0, description: "Applies to all sizes." }),
    defineItem("size:free", { code: "FREE", name: "Free Size", sort_order: 5, description: "Flexible free-size fit." }),
    defineItem("size:0-3m", { code: "0-3M", name: "0-3 Months", sort_order: 10, description: "Infant size." }),
    defineItem("size:3-6m", { code: "3-6M", name: "3-6 Months", sort_order: 20, description: "Infant size." }),
    defineItem("size:6-12m", { code: "6-12M", name: "6-12 Months", sort_order: 30, description: "Infant size." }),
    defineItem("size:1-2y", { code: "1-2Y", name: "1-2 Years", sort_order: 40, description: "Kids size." }),
    defineItem("size:2-3y", { code: "2-3Y", name: "2-3 Years", sort_order: 50, description: "Kids size." }),
    defineItem("size:3-4y", { code: "3-4Y", name: "3-4 Years", sort_order: 60, description: "Kids size." }),
    defineItem("size:4-5y", { code: "4-5Y", name: "4-5 Years", sort_order: 70, description: "Kids size." }),
    defineItem("size:5-6y", { code: "5-6Y", name: "5-6 Years", sort_order: 80, description: "Kids size." }),
    defineItem("size:6-7y", { code: "6-7Y", name: "6-7 Years", sort_order: 90, description: "Kids size." }),
    defineItem("size:7-8y", { code: "7-8Y", name: "7-8 Years", sort_order: 100, description: "Kids size." }),
    defineItem("size:8-9y", { code: "8-9Y", name: "8-9 Years", sort_order: 110, description: "Kids size." }),
    defineItem("size:9-10y", { code: "9-10Y", name: "9-10 Years", sort_order: 120, description: "Kids size." }),
    defineItem("size:10-11y", { code: "10-11Y", name: "10-11 Years", sort_order: 130, description: "Kids size." }),
    defineItem("size:11-12y", { code: "11-12Y", name: "11-12 Years", sort_order: 140, description: "Kids size." }),
    defineItem("size:12-13y", { code: "12-13Y", name: "12-13 Years", sort_order: 150, description: "Kids size." }),
    defineItem("size:13-14y", { code: "13-14Y", name: "13-14 Years", sort_order: 160, description: "Kids size." }),
    defineItem("size:xxs", { code: "XXS", name: "XX Small", sort_order: 170, description: "Adult size." }),
    defineItem("size:xs", { code: "XS", name: "X Small", sort_order: 180, description: "Adult size." }),
    defineItem("size:s", { code: "S", name: "Small", sort_order: 190, description: "Adult size." }),
    defineItem("size:m", { code: "M", name: "Medium", sort_order: 200, description: "Adult size." }),
    defineItem("size:l", { code: "L", name: "Large", sort_order: 210, description: "Adult size." }),
    defineItem("size:xl", { code: "XL", name: "X Large", sort_order: 220, description: "Adult size." }),
    defineItem("size:xxl", { code: "XXL", name: "XX Large", sort_order: 230, description: "Adult size." }),
    defineItem("size:3xl", { code: "3XL", name: "3X Large", sort_order: 240, description: "Adult size." }),
    defineItem("size:4xl", { code: "4XL", name: "4X Large", sort_order: 250, description: "Adult size." }),
    defineItem("size:5xl", { code: "5XL", name: "5X Large", sort_order: 260, description: "Adult size." }),
  ],
  orderTypes: [
    defineNamedModuleItem("order-type", "retail", "retail", "Retail Order", "Standard sell-side retail order flow."),
    defineNamedModuleItem("order-type", "wholesale", "wholesale", "Wholesale Order", "Bulk account or dealer order flow."),
  ],
  styles: [
    defineNamedModuleItem("style", "modern-ethnic", "modern-ethnic", "Modern Ethnic", "Modernized ethnic styling."),
    defineNamedModuleItem("style", "relaxed", "relaxed", "Relaxed", "Relaxed daily-wear styling."),
    defineNamedModuleItem("style", "basics", "basics", "Basics", "Everyday essential style direction."),
  ],
}
