import type { CommonModuleItem } from "../../../shared/index.js"

import {
  defineCity,
  defineCountry,
  defineDistrict,
  definePincode,
  defineState,
  type SeedMap,
} from "./helpers.js"

const indiaId = "country:india"
const tamilNaduId = "state:tamil-nadu"

const countries = [
  defineCountry("india", "IN", "India", "+91"),
  defineCountry("united-arab-emirates", "AE", "United Arab Emirates", "+971"),
  defineCountry("saudi-arabia", "SA", "Saudi Arabia", "+966"),
  defineCountry("singapore", "SG", "Singapore", "+65"),
  defineCountry("malaysia", "MY", "Malaysia", "+60"),
  defineCountry("sri-lanka", "LK", "Sri Lanka", "+94"),
  defineCountry("bangladesh", "BD", "Bangladesh", "+880"),
  defineCountry("nepal", "NP", "Nepal", "+977"),
  defineCountry("united-states", "US", "United States", "+1"),
  defineCountry("united-kingdom", "GB", "United Kingdom", "+44"),
  defineCountry("canada", "CA", "Canada", "+1"),
  defineCountry("australia", "AU", "Australia", "+61"),
  defineCountry("germany", "DE", "Germany", "+49"),
  defineCountry("france", "FR", "France", "+33"),
  defineCountry("italy", "IT", "Italy", "+39"),
  defineCountry("japan", "JP", "Japan", "+81"),
]

const indianStates = [
  ["andhra-pradesh", "AP", "Andhra Pradesh"],
  ["arunachal-pradesh", "AR", "Arunachal Pradesh"],
  ["assam", "AS", "Assam"],
  ["bihar", "BR", "Bihar"],
  ["chhattisgarh", "CG", "Chhattisgarh"],
  ["goa", "GA", "Goa"],
  ["gujarat", "GJ", "Gujarat"],
  ["haryana", "HR", "Haryana"],
  ["himachal-pradesh", "HP", "Himachal Pradesh"],
  ["jharkhand", "JH", "Jharkhand"],
  ["karnataka", "KA", "Karnataka"],
  ["kerala", "KL", "Kerala"],
  ["madhya-pradesh", "MP", "Madhya Pradesh"],
  ["maharashtra", "MH", "Maharashtra"],
  ["manipur", "MN", "Manipur"],
  ["meghalaya", "ML", "Meghalaya"],
  ["mizoram", "MZ", "Mizoram"],
  ["nagaland", "NL", "Nagaland"],
  ["odisha", "OD", "Odisha"],
  ["punjab", "PB", "Punjab"],
  ["rajasthan", "RJ", "Rajasthan"],
  ["sikkim", "SK", "Sikkim"],
  ["tamil-nadu", "TN", "Tamil Nadu"],
  ["telangana", "TS", "Telangana"],
  ["tripura", "TR", "Tripura"],
  ["uttar-pradesh", "UP", "Uttar Pradesh"],
  ["uttarakhand", "UK", "Uttarakhand"],
  ["west-bengal", "WB", "West Bengal"],
  ["andaman-and-nicobar-islands", "AN", "Andaman and Nicobar Islands"],
  ["chandigarh", "CH", "Chandigarh"],
  ["dadra-and-nagar-haveli-and-daman-and-diu", "DH", "Dadra and Nagar Haveli and Daman and Diu"],
  ["delhi", "DL", "Delhi"],
  ["jammu-and-kashmir", "JK", "Jammu and Kashmir"],
  ["ladakh", "LA", "Ladakh"],
  ["lakshadweep", "LD", "Lakshadweep"],
  ["puducherry", "PY", "Puducherry"],
] as const

const states = indianStates.map(([slug, code, name]) =>
  defineState(slug, indiaId, code, name)
)

const tamilNaduDistricts = [
  ["ariyalur", "TN-ARI", "Ariyalur"],
  ["chengalpattu", "TN-CGL", "Chengalpattu"],
  ["chennai", "TN-CHN", "Chennai"],
  ["coimbatore", "TN-CBE", "Coimbatore"],
  ["cuddalore", "TN-CUD", "Cuddalore"],
  ["dharmapuri", "TN-DPI", "Dharmapuri"],
  ["dindigul", "TN-DGL", "Dindigul"],
  ["erode", "TN-ERD", "Erode"],
  ["kallakurichi", "TN-KKI", "Kallakurichi"],
  ["kanchipuram", "TN-KPM", "Kanchipuram"],
  ["kanyakumari", "TN-KNK", "Kanyakumari"],
  ["karur", "TN-KRR", "Karur"],
  ["krishnagiri", "TN-KGI", "Krishnagiri"],
  ["madurai", "TN-MDU", "Madurai"],
  ["mayiladuthurai", "TN-MYD", "Mayiladuthurai"],
  ["nagapattinam", "TN-NGP", "Nagapattinam"],
  ["namakkal", "TN-NMK", "Namakkal"],
  ["nilgiris", "TN-NLG", "The Nilgiris"],
  ["perambalur", "TN-PER", "Perambalur"],
  ["pudukkottai", "TN-PDK", "Pudukkottai"],
  ["ramanathapuram", "TN-RMN", "Ramanathapuram"],
  ["ranipet", "TN-RPT", "Ranipet"],
  ["salem", "TN-SLM", "Salem"],
  ["sivaganga", "TN-SVG", "Sivaganga"],
  ["tenkasi", "TN-TKS", "Tenkasi"],
  ["thanjavur", "TN-TNJ", "Thanjavur"],
  ["theni", "TN-THN", "Theni"],
  ["thoothukudi", "TN-TTK", "Thoothukudi"],
  ["tiruchirappalli", "TN-TRI", "Tiruchirappalli"],
  ["tirunelveli", "TN-TNV", "Tirunelveli"],
  ["tirupattur", "TN-TPT", "Tirupattur"],
  ["tiruppur", "TN-TPR", "Tiruppur"],
  ["tiruvallur", "TN-TVL", "Tiruvallur"],
  ["tiruvannamalai", "TN-TVM", "Tiruvannamalai"],
  ["tiruvarur", "TN-TVR", "Tiruvarur"],
  ["vellore", "TN-VLR", "Vellore"],
  ["villupuram", "TN-VPM", "Viluppuram"],
  ["virudhunagar", "TN-VNR", "Virudhunagar"],
] as const

const tnDistrictItems = tamilNaduDistricts.map(([slug, code, name]) =>
  defineDistrict(slug, tamilNaduId, code, name)
)

const majorDistricts = [
  defineDistrict("bengaluru-urban", "state:karnataka", "KA-BLR", "Bengaluru Urban"),
  defineDistrict("mumbai", "state:maharashtra", "MH-MUM", "Mumbai"),
  defineDistrict("new-delhi", "state:delhi", "DL-ND", "New Delhi"),
  defineDistrict("hyderabad", "state:telangana", "TS-HYD", "Hyderabad"),
  defineDistrict("kolkata", "state:west-bengal", "WB-KOL", "Kolkata"),
  defineDistrict("pune", "state:maharashtra", "MH-PUN", "Pune"),
  defineDistrict("ahmedabad", "state:gujarat", "GJ-AHM", "Ahmedabad"),
  defineDistrict("ernakulam", "state:kerala", "KL-ERN", "Ernakulam"),
  defineDistrict("jaipur", "state:rajasthan", "RJ-JAI", "Jaipur"),
  defineDistrict("surat", "state:gujarat", "GJ-SRT", "Surat"),
  defineDistrict("lucknow", "state:uttar-pradesh", "UP-LKO", "Lucknow"),
  defineDistrict("visakhapatnam", "state:andhra-pradesh", "AP-VSK", "Visakhapatnam"),
]

const tamilNaduCities = [
  ["chennai", "district:chennai", "MAA", "Chennai"],
  ["coimbatore", "district:coimbatore", "CBE", "Coimbatore"],
  ["tiruppur", "district:tiruppur", "TPR", "Tiruppur"],
  ["madurai", "district:madurai", "IXM", "Madurai"],
  ["salem", "district:salem", "SLM", "Salem"],
  ["erode", "district:erode", "ERD", "Erode"],
  ["tiruchirappalli", "district:tiruchirappalli", "TRZ", "Tiruchirappalli"],
  ["vellore", "district:vellore", "VLR", "Vellore"],
  ["thanjavur", "district:thanjavur", "TNJ", "Thanjavur"],
  ["dindigul", "district:dindigul", "DGL", "Dindigul"],
  ["namakkal", "district:namakkal", "NMK", "Namakkal"],
  ["karur", "district:karur", "KRR", "Karur"],
  ["tirunelveli", "district:tirunelveli", "TEN", "Tirunelveli"],
  ["thoothukudi", "district:thoothukudi", "TUT", "Thoothukudi"],
  ["nagercoil", "district:kanyakumari", "NGL", "Nagercoil"],
  ["kanchipuram", "district:kanchipuram", "KPM", "Kanchipuram"],
  ["chengalpattu", "district:chengalpattu", "CGL", "Chengalpattu"],
  ["tiruvallur", "district:tiruvallur", "TVL", "Tiruvallur"],
  ["tiruvannamalai", "district:tiruvannamalai", "TVM", "Tiruvannamalai"],
  ["cuddalore", "district:cuddalore", "CUD", "Cuddalore"],
  ["villupuram", "district:villupuram", "VPM", "Viluppuram"],
  ["kallakurichi", "district:kallakurichi", "KKI", "Kallakurichi"],
  ["nagapattinam", "district:nagapattinam", "NGP", "Nagapattinam"],
  ["mayiladuthurai", "district:mayiladuthurai", "MYD", "Mayiladuthurai"],
  ["tiruvarur", "district:tiruvarur", "TVR", "Tiruvarur"],
  ["sivaganga", "district:sivaganga", "SVG", "Sivaganga"],
  ["ramanathapuram", "district:ramanathapuram", "RMN", "Ramanathapuram"],
  ["virudhunagar", "district:virudhunagar", "VNR", "Virudhunagar"],
  ["theni", "district:theni", "THN", "Theni"],
  ["tenkasi", "district:tenkasi", "TKS", "Tenkasi"],
  ["dharmapuri", "district:dharmapuri", "DPI", "Dharmapuri"],
  ["krishnagiri", "district:krishnagiri", "KGI", "Krishnagiri"],
  ["ranipet", "district:ranipet", "RPT", "Ranipet"],
  ["tirupattur", "district:tirupattur", "TPT", "Tirupattur"],
  ["perambalur", "district:perambalur", "PER", "Perambalur"],
  ["ariyalur", "district:ariyalur", "ARI", "Ariyalur"],
  ["pudukkottai", "district:pudukkottai", "PDK", "Pudukkottai"],
  ["ooty", "district:nilgiris", "OOT", "Ooty"],
] as const

const tnCityItems = tamilNaduCities.map(([slug, districtId, code, name]) =>
  defineCity(slug, tamilNaduId, districtId, code, name)
)

const majorIndianCities = [
  defineCity("bengaluru", "state:karnataka", "district:bengaluru-urban", "BLR", "Bengaluru"),
  defineCity("mumbai", "state:maharashtra", "district:mumbai", "BOM", "Mumbai"),
  defineCity("new-delhi", "state:delhi", "district:new-delhi", "DEL", "New Delhi"),
  defineCity("hyderabad", "state:telangana", "district:hyderabad", "HYD", "Hyderabad"),
  defineCity("kolkata", "state:west-bengal", "district:kolkata", "CCU", "Kolkata"),
  defineCity("pune", "state:maharashtra", "district:pune", "PNQ", "Pune"),
  defineCity("ahmedabad", "state:gujarat", "district:ahmedabad", "AMD", "Ahmedabad"),
  defineCity("kochi", "state:kerala", "district:ernakulam", "COK", "Kochi"),
  defineCity("jaipur", "state:rajasthan", "district:jaipur", "JAI", "Jaipur"),
  defineCity("surat", "state:gujarat", "district:surat", "STV", "Surat"),
  defineCity("lucknow", "state:uttar-pradesh", "district:lucknow", "LKO", "Lucknow"),
  defineCity("visakhapatnam", "state:andhra-pradesh", "district:visakhapatnam", "VTZ", "Visakhapatnam"),
]

const pincodes = [
  definePincode({ code: "600001", areaName: "George Town", countryId: indiaId, stateId: tamilNaduId, districtId: "district:chennai", cityId: "city:chennai" }),
  definePincode({ code: "600004", areaName: "Mylapore", countryId: indiaId, stateId: tamilNaduId, districtId: "district:chennai", cityId: "city:chennai" }),
  definePincode({ code: "600006", areaName: "Nungambakkam", countryId: indiaId, stateId: tamilNaduId, districtId: "district:chennai", cityId: "city:chennai" }),
  definePincode({ code: "600017", areaName: "T Nagar", countryId: indiaId, stateId: tamilNaduId, districtId: "district:chennai", cityId: "city:chennai" }),
  definePincode({ code: "600028", areaName: "RA Puram", countryId: indiaId, stateId: tamilNaduId, districtId: "district:chennai", cityId: "city:chennai" }),
  definePincode({ code: "600032", areaName: "Guindy", countryId: indiaId, stateId: tamilNaduId, districtId: "district:chennai", cityId: "city:chennai" }),
  definePincode({ code: "600040", areaName: "Anna Nagar", countryId: indiaId, stateId: tamilNaduId, districtId: "district:chennai", cityId: "city:chennai" }),
  definePincode({ code: "600042", areaName: "Velachery", countryId: indiaId, stateId: tamilNaduId, districtId: "district:chennai", cityId: "city:chennai" }),
  definePincode({ code: "600083", areaName: "Ashok Nagar", countryId: indiaId, stateId: tamilNaduId, districtId: "district:chennai", cityId: "city:chennai" }),
  definePincode({ code: "641001", areaName: "Town Hall", countryId: indiaId, stateId: tamilNaduId, districtId: "district:coimbatore", cityId: "city:coimbatore" }),
  definePincode({ code: "641002", areaName: "RS Puram", countryId: indiaId, stateId: tamilNaduId, districtId: "district:coimbatore", cityId: "city:coimbatore" }),
  definePincode({ code: "641004", areaName: "Peelamedu", countryId: indiaId, stateId: tamilNaduId, districtId: "district:coimbatore", cityId: "city:coimbatore" }),
  definePincode({ code: "641014", areaName: "Civil Aerodrome", countryId: indiaId, stateId: tamilNaduId, districtId: "district:coimbatore", cityId: "city:coimbatore" }),
  definePincode({ code: "641018", areaName: "Coimbatore Central", countryId: indiaId, stateId: tamilNaduId, districtId: "district:coimbatore", cityId: "city:coimbatore" }),
  definePincode({ code: "641035", areaName: "Saravanampatti", countryId: indiaId, stateId: tamilNaduId, districtId: "district:coimbatore", cityId: "city:coimbatore" }),
  definePincode({ code: "641037", areaName: "Gandhipuram", countryId: indiaId, stateId: tamilNaduId, districtId: "district:coimbatore", cityId: "city:coimbatore" }),
  definePincode({ code: "641601", areaName: "Tiruppur", countryId: indiaId, stateId: tamilNaduId, districtId: "district:tiruppur", cityId: "city:tiruppur" }),
  definePincode({ code: "641602", areaName: "Rayapuram", countryId: indiaId, stateId: tamilNaduId, districtId: "district:tiruppur", cityId: "city:tiruppur" }),
  definePincode({ code: "641603", areaName: "Palladam Road", countryId: indiaId, stateId: tamilNaduId, districtId: "district:tiruppur", cityId: "city:tiruppur" }),
  definePincode({ code: "641604", areaName: "Avinashi Road", countryId: indiaId, stateId: tamilNaduId, districtId: "district:tiruppur", cityId: "city:tiruppur" }),
  definePincode({ code: "641605", areaName: "Dharapuram Road", countryId: indiaId, stateId: tamilNaduId, districtId: "district:tiruppur", cityId: "city:tiruppur" }),
  definePincode({ code: "560001", areaName: "MG Road", countryId: indiaId, stateId: "state:karnataka", districtId: "district:bengaluru-urban", cityId: "city:bengaluru" }),
] satisfies CommonModuleItem[]

export const locationSeed: SeedMap = {
  countries,
  states,
  districts: [...tnDistrictItems, ...majorDistricts],
  cities: [...tnCityItems, ...majorIndianCities],
  pincodes,
}
