import { defineAppWorkspace } from "../src/application/app-workspace.js"

export const frameworkAppWorkspace = defineAppWorkspace("framework", "Framework")
export * from "./activity-log.js"
export * from "./app-settings.js"
export * from "./application-version.js"
export * from "./database-operations.js"
export * from "./mail-settings.js"
export * from "./media.js"
export * from "./module-manifest.js"
export * from "./module-manifest.examples.js"
export * from "./monitoring.js"
export * from "./runtime-jobs.js"
export * from "./runtime-settings.js"
export * from "./developer-operations.js"
export * from "./hosted-apps.js"
export * from "./remote-server-status.js"
export * from "./remote-server-control.js"
